<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Bella Ratmelia">
  <title>Introductory R for Social Sciences – Session 4: Basic Inferential Stats in R</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-49bde94825fa39fb910dd92406f11d8e.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Session 4: Basic Inferential Stats in R</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bella Ratmelia 
</div>
</div>
</div>

</section>
<section id="todays-outline" class="slide level2">
<h2>Today’s Outline</h2>
<p>Today is really about <em>With these variables that I have, which test do I reach for?</em></p>
<ol type="1">
<li>Both categorical → <strong>chi-square</strong></li>
<li>Both continuous → <strong>correlation</strong></li>
<li>Categorical (2 groups) + continuous → <strong>t-tests</strong></li>
<li>Categorical (3+ groups) + continuous → <strong>ANOVA</strong></li>
</ol>
</section>
<section id="refresher-data-distribution" class="slide level2">
<h2>Refresher: Data Distribution</h2>
<p>The choice of appropriate statistical tests and methods often depends on the distribution of the data. Understanding the distribution helps in selecting the right test and judging its validity.</p>

<img data-src="04-stats_files/figure-revealjs/unnamed-chunk-1-1.png" width="1344" class="r-stretch"></section>
<section id="refresher-research-variables" class="slide level2">
<h2>Refresher: Research Variables</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><u><strong>Dependent Variable (DV)</strong></u></p>
<p>The variables that will be affected as a result of manipulation/changes in the IVs</p>
<ul>
<li>Other names for it: Outcome, Response, Output, etc.</li>
<li>Often denoted as <span class="math inline">\(y\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p><u><strong>Independent Variable (IV)</strong></u></p>
<p>The variables that researchers will manipulate.</p>
<ul>
<li>Other names for it: Predictor, Covariate, Treatment, Regressor, Input, etc.</li>
<li>Often denoted as <span class="math inline">\(x\)</span></li>
</ul>
</div></div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Naming your DV and IV (and their data type) <em>is</em> the first step in the whole process. Do this before you write a single line of code (or ask an AI for any).</p>
</div>
</div>
</div>
</section>
<section id="choosing-a-test-from-your-variables" class="slide level2">
<h2>Choosing a test from your variables</h2>
<p>Almost every test today comes down to reading the <strong>types</strong> of your variables :</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 42%">
<col style="width: 46%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Dependent variable (Y)</th>
<th>Independent variable (X)</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td><strong>Chi-square</strong> test of independence</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Continuous</td>
<td><strong>Correlation</strong> (Pearson / Spearman / Kendall)</td>
</tr>
<tr class="odd">
<td>Continuous</td>
<td>Categorical, <strong>2 groups</strong></td>
<td><strong>t-test</strong></td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Categorical, <strong>3+ groups</strong></td>
<td><strong>ANOVA</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Remember, you are responsible for your work. <em>“Because Claude/ChatGPT told me this is the answer”</em> is not a defensible answer when your professor asks you about your analysis.</p>
</div>
</div>
</div>
</section>
<section id="checklist-when-you-start-rstudio" class="slide level2">
<h2>Checklist when you start RStudio</h2>
<ol type="1">
<li><p>Go to the folder where you put your project for this workshop</p></li>
<li><p>Find a file with <code>.Rproj</code> extension - this is the R project file that holds all the information about your project.</p></li>
</ol>

<img data-src="images/locate-rproj-file.jpg" class="r-stretch"><ol start="3" type="1">
<li>Double click on the file. Rstudio should launch with your project loaded!</li>
</ol>
<p>Optional (Though best practice):</p>
<ul>
<li>Make sure that <code>Environment</code> panel is empty (click on broom icon to clean it up).</li>
<li>Clear the <code>Console</code> and <code>Plots</code> too.</li>
</ul>
</section>
<section id="load-our-data-for-today" class="slide level2">
<h2>Load our data for today!</h2>
<p>Let’s create a new R script called <code>session-4.R</code>, and then copy the code below to load our data for today. This code uses <code>read_csv</code> from <code>readr</code> package (part of <code>tidyverse</code>) to load our cleaned CSV (from the first checkpoint)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># import tidyverse library</span></span>
<span id="cb1-2"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a><span class="co"># read the CSV with WVS data</span></span>
<span id="cb1-5"><a></a>wvs_cleaned <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data-output/wvs_cleaned_v1.csv"</span>)</span>
<span id="cb1-6"><a></a></span>
<span id="cb1-7"><a></a><span class="co"># Convert categorical variables to factors</span></span>
<span id="cb1-8"><a></a>columns_to_convert <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"sex"</span>, <span class="st">"marital_status"</span>, <span class="st">"urban_rural"</span>, <span class="st">"income_level"</span>, <span class="st">"education"</span>, <span class="st">"trust_people"</span>)</span>
<span id="cb1-9"><a></a></span>
<span id="cb1-10"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(columns_to_convert), as_factor))</span>
<span id="cb1-12"><a></a></span>
<span id="cb1-13"><a></a><span class="co"># put income_level in a natural low-to-high order (instead of alphabetical)</span></span>
<span id="cb1-14"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb1-15"><a></a>    <span class="fu">mutate</span>(<span class="at">income_level =</span> <span class="fu">factor</span>(income_level, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>)))</span>
<span id="cb1-16"><a></a></span>
<span id="cb1-17"><a></a><span class="co"># peek at the data, pay attention to the data types!</span></span>
<span id="cb1-18"><a></a><span class="fu">glimpse</span>(wvs_cleaned)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section>
<section id="both-categorical-the-x2-test" class="title-slide slide level1 center">
<h1>Both categorical → The <span class="math inline">\(X^2\)</span> test</h1>

</section>
<section id="where-we-are-right-now" class="slide level2">
<h2>Where we are right now</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Y</th>
<th>X</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Categorical</strong></td>
<td><strong>Categorical</strong></td>
<td>← <strong>Chi-square</strong></td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Continuous</td>
<td>Correlation</td>
</tr>
<tr class="odd">
<td>Continuous</td>
<td>Categorical (2)</td>
<td>t-test</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Categorical (3+)</td>
<td>ANOVA</td>
</tr>
</tbody>
</table>
</section>
<section id="chi-square-test-of-independence" class="slide level2">
<h2>Chi-square test of independence</h2>
<p>The <span class="math inline">\(X^2\)</span> test of independence evaluates whether there is a statistically significant relationship between two categorical variables.</p>
<p>This is done by analyzing the frequency table (i.e., contingency table) formed by two categorical variables.</p>
<p><strong>Example</strong>: Is there a relationship between <code>education</code> level and <code>income_level</code> in our WVS data?</p>
<p>Typically, we can start with the contingency table first, and then the visualization</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">table</span>(wvs_cleaned<span class="sc">$</span>education, wvs_cleaned<span class="sc">$</span>income_level)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
          Low Medium High
  Lower   937   1298  157
  Middle  315   1048  121
  Higher  170    901  155</code></pre>
</div>
</div>
</section>
<section id="chi-square-test-of-independence---visualizing-data" class="slide level2">
<h2>Chi-square test of independence - visualizing data</h2>
<p>We can use percent-stacked bar chart to visualize this (remember from last week!)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> income_level, <span class="at">fill =</span> education)) <span class="sc">+</span></span>
<span id="cb4-3"><a></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportion of education level for each income level"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="04-stats_files/figure-revealjs/unnamed-chunk-3-1.png" width="1344" class="r-stretch"></section>
<section id="chi-square-sample-problem-and-results" class="slide level2">
<h2>Chi-Square: Sample problem and results</h2>
<p>Is there a relationship between education level and income level?</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: Education level and income level are <strong>independent</strong> (no association).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: Education level and income level are <strong>not independent</strong> (associated).</p>
</div></div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(wvs_cleaned<span class="sc">$</span>education, wvs_cleaned<span class="sc">$</span>income_level))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(wvs_cleaned$education, wvs_cleaned$income_level)
X-squared = 318.06, df = 4, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<div style="font-size: 75%; width: 75%">
<ul>
<li><strong>X-squared</strong> = the coefficient</li>
<li><strong>df</strong> = degree of freedom</li>
<li><strong>p-value</strong> = the probability of getting more extreme results than what was observed. Generally, if this value is less than the pre-determined significance level (also called alpha), the result would be considered “statistically significant”</li>
</ul>
</div>
<p><em>Given the hypotheses above, how would you narrate this result in your report?</em></p>
</section>
<section id="reporting-χ²-in-apa-style" class="slide level2">
<h2>Reporting χ² in APA style</h2>
<p>Report the statistic with its <strong>degrees of freedom</strong> and <strong>sample size</strong>, then the value and p:</p>
<p><span class="math display">\[\chi^2(4,\ N = 5102) = 318.06,\ p &lt; .001\]</span></p>
<ul>
<li><code>df</code> (4) and <code>X-squared</code> (318.06) come straight from the test output</li>
<li><span class="math inline">\(N\)</span> (5102) is your total number of observations</li>
<li>For a table with <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns, <span class="math inline">\(df = (r-1)(c-1)\)</span></li>
</ul>
</section></section>
<section>
<section id="both-continuous-correlation" class="title-slide slide level1 center">
<h1>Both continuous → Correlation</h1>

</section>
<section id="where-we-are-right-now-1" class="slide level2">
<h2>Where we are right now</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Y</th>
<th>X</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td>Chi-square</td>
</tr>
<tr class="even">
<td><strong>Continuous</strong></td>
<td><strong>Continuous</strong></td>
<td>← <strong>Correlation</strong></td>
</tr>
<tr class="odd">
<td>Continuous</td>
<td>Categorical (2)</td>
<td>t-test</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Categorical (3+)</td>
<td>ANOVA</td>
</tr>
</tbody>
</table>
</section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<p>A correlation test evaluates the strength and direction of a linear relationship between two variables. The coefficient is expressed in value between -1 to 1, with 0 being no correlation at all.</p>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>Pearson’s</strong> <span class="math inline">\(r\)</span> (r)</p>
<ul>
<li>Measure the association between two continuous numerical variables</li>
<li>Sensitive to outliers</li>
<li>Assumes normality and/or linearity</li>
<li>(<em>most likely the one that you learned in class)</em></li>
</ul>
</div><div class="column" style="width:33%;">
<p><strong>Kendall’s</strong> <span class="math inline">\(\tau\)</span> (tau)</p>
<ul>
<li>Measure the association between two variables (ordinal-ordinal or ordinal-continuous)</li>
<li>less sensitive/more robust to outliers</li>
<li>non-parametric, does not assume normality and/or linearity</li>
</ul>
</div><div class="column" style="width:33%;">
<p><strong>Spearman’s</strong> <span class="math inline">\(\rho\)</span> (rho)</p>
<ul>
<li>Measure the association between two variables (ordinal-ordinal or ordinal-continuous)</li>
<li>less sensitive/more robust to outliers</li>
<li>non-parametric, does not assume normality and/or linearity</li>
</ul>
</div></div>
<p>For more info, you can refer to this reading: <a href="https://journals.sagepub.com/doi/pdf/10.1177/8756479308317006" target="_blank">Measures of Association - How to Choose? (Harry Khamis, PhD)</a></p>
</section>
<section id="correlation-sample-problem-and-result" class="slide level2">
<h2>Correlation: Sample problem and result</h2>
<p>RQ: <strong>Is there a significant correlation between emancipative values and secular values?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: There is <strong>no</strong> linear correlation between emancipative and secular values (<span class="math inline">\(\rho = 0\)</span>).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: There <strong>is</strong> a linear correlation between emancipative and secular values (<span class="math inline">\(\rho \neq 0\)</span>).</p>
</div></div>
<p>As both variables are numerical and continuous, we can use pearson correlation.</p>
<p>Let’s start with visualizing the data, which can be used to support the explanation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> secular_values, <span class="at">y =</span> emancipative_values)) <span class="sc">+</span></span>
<span id="cb7-3"><a></a>    <span class="fu">geom_jitter</span>(<span class="at">color=</span><span class="st">"maroon"</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="co"># se shows the confidence interval</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="correlation-sample-problem-and-result-output" class="slide level2 output-location-slide"><h2>Correlation: Sample problem and result</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-5-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="conduct-the-correlation-test" class="slide level2">
<h2>Conduct the correlation test</h2>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">cor.test</span>(wvs_cleaned<span class="sc">$</span>emancipative_values,</span>
<span id="cb8-2"><a></a>         wvs_cleaned<span class="sc">$</span>secular_values,</span>
<span id="cb8-3"><a></a>         <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  wvs_cleaned$emancipative_values and wvs_cleaned$secular_values
t = 36.765, df = 5100, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4357486 0.4791391
sample estimates:
      cor 
0.4577163 </code></pre>
</div>
</div></div>
<div style="font-size: 75%; width: 75%">
<ul>
<li><strong>cor</strong> is the <strong>correlation coefficient</strong> - this is the number that you want to report.</li>
<li><strong>t</strong> is the <strong>t-test statistic</strong></li>
<li><strong>df</strong> is the degrees of freedom</li>
<li><strong>p-value</strong> is the significance level of the <strong>t-test</strong></li>
<li><strong>conf.int</strong> is the <strong>confidence interval</strong> of the coefficient at 95%</li>
<li><strong>sample estimates</strong> is the correlation coefficient</li>
</ul>
</div>
</section>
<section id="reporting-r-in-apa-style" class="slide level2">
<h2>Reporting r in APA style</h2>
<p>Report Pearson’s correlation with its <strong>degrees of freedom</strong> in parentheses, the coefficient, and p:</p>
<p><span class="math display">\[r(5100) = .46,\ p &lt; .001\]</span></p>
<ul>
<li><code>df</code> (5100) and <code>cor</code> (.46) are in the test output (here <span class="math inline">\(df = N - 2\)</span>)</li>
<li>Good practice is to add the 95% CI too: <em>r</em>(5100) = .46, 95% CI [.44, .48], <em>p</em> &lt; .001</li>
<li><em>(APA rounds r to 2 decimals and drops the leading zero.)</em></li>
</ul>
</section>
<section id="learning-check-1" class="slide level2">
<h2>Learning Check #1</h2>
<p>Look at the map. <code>urban_rural</code> and <code>trust_people</code> are <strong>both categorical</strong> — so which test do you reach for?</p>
<p>Is there a relationship between where someone lives (<code>urban_rural</code>) and whether they trust others (<code>trust_people</code>)? Is the result aligned with what you expected?</p>
<p><em>First, try stating <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> yourself — then run the test.</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(wvs_cleaned<span class="sc">$</span>urban_rural, wvs_cleaned<span class="sc">$</span>trust_people))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(wvs_cleaned$urban_rural, wvs_cleaned$trust_people)
X-squared = 157.66, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</section></section>
<section>
<section id="categorical-2-groups-continuous-t-tests" class="title-slide slide level1 center">
<h1>Categorical (2 groups) + continuous → T-Tests</h1>

</section>
<section id="where-we-are-right-now-2" class="slide level2">
<h2>Where we are right now</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Y</th>
<th>X</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td>Chi-square</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Continuous</td>
<td>Correlation</td>
</tr>
<tr class="odd">
<td><strong>Continuous</strong></td>
<td><strong>Categorical (2)</strong></td>
<td>← <strong>t-test</strong></td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Categorical (3+)</td>
<td>ANOVA</td>
</tr>
</tbody>
</table>
</section>
<section id="t-tests" class="slide level2">
<h2>T-Tests</h2>
<p>A <strong>t-test</strong> is a statistical test used to compare the means of two groups/samples of continuous data type and determine if the differences are statistically significant.</p>
<ul>
<li>The Student’s <em>t</em>-test is widely used when the sample size is reasonably small (less than approximately 30) <strong>or</strong> when the population standard deviation is unknown.</li>
</ul>
</section>
<section id="types-of-t-test" class="slide level2">
<h2>3 types of t-test</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><strong>Two-samples / Independent Samples T-test</strong></p>
<p>Used to compare the means of two independent groups (such as between-subjects research) to determine if they are significantly different.</p>
<p>Examples: Men vs Women group, Placebo vs Actual drugs.</p>
</div><div class="column" style="width:30%;">
<p><strong>Paired Samples T-Test</strong></p>
<p>Used to compare the means of two related groups, such as repeated measurements on the same subjects (within-subjects research).</p>
<p>Examples: Before workshop vs After workshop.</p>
</div><div class="column" style="width:30%;">
<p><strong>One-sample T-test</strong></p>
<p>Test if a specific sample mean (X̄) is statistically different from a known or hypothesized population mean (μ or mu)</p>
</div></div>
</section>
<section id="t-test-independent-samples-t-test" class="slide level2">
<h2>T-Test: Independent Samples T-Test</h2>
<p>RQ: <strong>Is there a significant difference in secular values between urban and rural residents?</strong></p>
<p>Let’s first take only the necessary columns and get some summary statistics, particularly on the number of samples for each group, as well as the mean, standard deviation, and variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a></a>    <span class="fu">group_by</span>(urban_rural) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a></a>    <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">n</span>(),</span>
<span id="cb12-4"><a></a>              <span class="at">mean =</span> <span class="fu">mean</span>(secular_values),</span>
<span id="cb12-5"><a></a>              <span class="at">variance =</span> <span class="fu">var</span>(secular_values),</span>
<span id="cb12-6"><a></a>              <span class="at">stdeviation =</span> <span class="fu">sd</span>(secular_values))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  urban_rural total  mean variance stdeviation
  &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
1 Urban        3312 0.392   0.0352       0.187
2 Rural        1790 0.282   0.0203       0.143</code></pre>
</div>
</div>
</section>
<section id="visualize-the-differences-between-two-samples" class="slide level2">
<h2>Visualize the differences between two samples</h2>
<p>The variance will be easier to see when we visualize it as well.</p>
<p>Here, the two groups have somewhat different spreads (the urban group is more variable), which suggests the variances may not be homogeneous. In this case, we can consider switching to <strong>Welch’s t-test</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> urban_rural, <span class="at">y =</span> secular_values)) <span class="sc">+</span></span>
<span id="cb14-3"><a></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-4"><a></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="visualize-the-differences-between-two-samples-output" class="slide level2 output-location-slide"><h2>Visualize the differences between two samples</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-9-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="conduct-the-independent-samples-t-test" class="slide level2">
<h2>Conduct the independent samples T-test</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: Mean secular values are <strong>equal</strong> for urban and rural residents (<span class="math inline">\(\mu_{urban} = \mu_{rural}\)</span>).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: Mean secular values are <strong>different</strong> between urban and rural residents (<span class="math inline">\(\mu_{urban} \neq \mu_{rural}\)</span>).</p>
</div></div>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">t.test</span>(secular_values <span class="sc">~</span> urban_rural,</span>
<span id="cb15-2"><a></a>       <span class="at">data =</span> wvs_cleaned,</span>
<span id="cb15-3"><a></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="co"># you can swap this with 'greater' or 'less'</span></span>
<span id="cb15-4"><a></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  secular_values by urban_rural
t = 23.417, df = 4547.9, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Urban and group Rural is not equal to 0
95 percent confidence interval:
 0.1005909 0.1189729
sample estimates:
mean in group Urban mean in group Rural 
          0.3918647           0.2820828 </code></pre>
</div>
</div></div>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Notice that we are using Welch’s t-test instead of Students’ t-test</strong></p>
</div>
<div class="callout-content">
<p>Welch’s t-test (also known as <strong>unequal variances t-test</strong>, is a more robust alternative to Student’s t-test. It is often used when two samples have unequal variances and possibly unequal sample sizes. By default, the <code>t.test</code> function in R will run Welch’s t-test.</p>
</div>
</div>
</div>
</section>
<section id="reporting-t-in-apa-style-independent-samples" class="slide level2">
<h2>Reporting t in APA style (independent samples)</h2>
<p>Report the <strong>degrees of freedom</strong>, the t statistic, and p:</p>
<p><span class="math display">\[t(4547.9) = 23.42,\ p &lt; .001\]</span></p>
<ul>
<li>Read <code>df</code> and <code>t</code> from the test output. With <strong>Welch’s</strong> t-test the <code>df</code> is often a decimal — report it as shown.</li>
<li>Good practice is to also give each group’s mean, e.g.&nbsp;urban (<em>M</em> = 0.39) vs rural (<em>M</em> = 0.28).</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>The same <code>t(df)</code> format is used for <strong>every</strong> t-test — see the next slides for the paired and one-sample versions.</p>
</div>
</div>
</div>
</section>
<section id="t-test-paired-sample-t-test" class="slide level2">
<h2>T-Test: Paired Sample T-Test</h2>
<p>Unfortunately, our data is not suitable for paired T-Test.</p>
<p>For demo purposes, we are going to use a built-in sample datasets called <code>sleep</code> from the base R dataset.</p>
<p>The dataset is already loaded, so you can use it right away!</p>
<ul>
<li>type <code>View(sleep)</code> in your R console (bottom left), and then press enter. RStudio will open up the preview of the dataset.</li>
<li>type <code>?sleep</code> in your R console to view the help page (a.k.a vignette) about this dataset.</li>
<li>type <code>data()</code> in your console to see what are the available datasets that you can use for practice!</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>sleep <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(sleep)</span>
<span id="cb17-2"><a></a><span class="fu">print</span>(sleep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="t-test-paired-sample-t-test-output" class="slide level2 output-location-slide"><h2>T-Test: Paired Sample T-Test</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   extra group ID   
   &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;
 1   0.7 1     1    
 2  -1.6 1     2    
 3  -0.2 1     3    
 4  -1.2 1     4    
 5  -0.1 1     5    
 6   3.4 1     6    
 7   3.7 1     7    
 8   0.8 1     8    
 9   0   1     9    
10   2   1     10   
11   1.9 2     1    
12   0.8 2     2    
13   1.1 2     3    
14   0.1 2     4    
15  -0.1 2     5    
16   4.4 2     6    
17   5.5 2     7    
18   1.6 2     8    
19   4.6 2     9    
20   3.4 2     10   </code></pre>
</div>
</div></section><section id="some-note-about-sleep-data" class="slide level2">
<h2>Some note about Sleep data</h2>
<p>(from <code>?sleep</code>)</p>
<p><strong>Format</strong></p>
<p>A data frame with 20 observations on 3 variables.</p>
<pre><code>[, 1]   extra   numeric increase in hours of sleep
[, 2]   group   factor  drug given
[, 3]   ID  factor  patient ID</code></pre>
<p><strong>Details</strong></p>
<p>The group variable name may be misleading about the data: They represent measurements on 10 persons, not in groups.</p>
</section>
<section id="visualize-the-before-group-1-and-after-group-2" class="slide level2">
<h2>Visualize the before (group 1) and after (group 2)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>sleep <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a></a>    <span class="fu">group_by</span>(group) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a></a>    <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">mean =</span> <span class="fu">mean</span>(extra), <span class="at">sd =</span> <span class="fu">sd</span>(extra), <span class="at">variance =</span> <span class="fu">var</span>(extra))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  group     n  mean    sd variance
  &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1 1        10  0.75  1.79     3.20
2 2        10  2.33  2.00     4.01</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>Visualization:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>sleep <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> extra)) <span class="sc">+</span></span>
<span id="cb22-3"><a></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="" class="slide level2 output-location-slide"><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-13-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="transform-the-data-shape" class="slide level2">
<h2>Transform the data shape</h2>
<p>The data is in long format. Let’s transform it into wide format so that we can conduct the analysis more easily.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>sleep_wide <span class="ot">&lt;-</span> sleep <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> group, <span class="at">values_from =</span> extra,</span>
<span id="cb23-3"><a></a>                <span class="at">names_prefix =</span> <span class="st">"group_"</span>)</span>
<span id="cb23-4"><a></a><span class="fu">print</span>(sleep_wide)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   ID    group_1 group_2
   &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 1         0.7     1.9
 2 2        -1.6     0.8
 3 3        -0.2     1.1
 4 4        -1.2     0.1
 5 5        -0.1    -0.1
 6 6         3.4     4.4
 7 7         3.7     5.5
 8 8         0.8     1.6
 9 9         0       4.6
10 10        2       3.4</code></pre>
</div>
</div>
</section>
<section id="conduct-the-paired-sample-t-test" class="slide level2">
<h2>Conduct the paired-sample T-test</h2>
<p>Remember, the hypotheses are:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: The mean difference in extra sleep between the two drugs is <strong>zero</strong> (<span class="math inline">\(\mu_d = 0\)</span>).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: The mean difference in extra sleep between the two drugs is <strong>not zero</strong> (<span class="math inline">\(\mu_d \neq 0\)</span>).</p>
</div></div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">t.test</span>(<span class="fu">Pair</span>(sleep_wide<span class="sc">$</span>group_1, sleep_wide<span class="sc">$</span>group_2) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb25-2"><a></a>       <span class="at">data =</span> sleep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Pair(sleep_wide$group_1, sleep_wide$group_2)
t = -4.0621, df = 9, p-value = 0.002833
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.4598858 -0.7001142
sample estimates:
mean difference 
          -1.58 </code></pre>
</div>
</div>
</section>
<section id="reporting-t-in-apa-style-paired" class="slide level2">
<h2>Reporting t in APA style (paired)</h2>
<p><span class="math display">\[t(9) = -4.06,\ p = .003\]</span></p>
<ul>
<li>Same <code>t(df)</code> format — here with a small sample, <code>df</code> = 9.</li>
<li>Note <code>p</code> is reported as <code>p = .003</code> (not <code>&lt; .001</code>), since it’s above that threshold.</li>
</ul>
</section>
<section id="t-test-one-sample-t-test" class="slide level2">
<h2>T-test: One-sample T-Test</h2>
<p>RQ: <strong>Is the average life satisfaction in our sample significantly different from the global average of 6.5?</strong></p>
<p>Let’s start with visualizing the data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> life_satisfaction)) <span class="sc">+</span></span>
<span id="cb27-3"><a></a>    <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">6.5</span>, <span class="at">color=</span><span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-16-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conduct-the-one-sample-t-test" class="slide level2">
<h2>Conduct the One-sample T-Test</h2>
<p>Remember, the hypotheses are:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: Mean life satisfaction is <strong>equal</strong> to 6.5 (<span class="math inline">\(\mu = 6.5\)</span>).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: Mean life satisfaction is <strong>different</strong> from 6.5 (<span class="math inline">\(\mu \neq 6.5\)</span>).</p>
</div></div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>global_mean_satisfaction <span class="ot">=</span> <span class="fl">6.5</span></span>
<span id="cb28-2"><a></a></span>
<span id="cb28-3"><a></a><span class="fu">t.test</span>(wvs_cleaned<span class="sc">$</span>life_satisfaction,</span>
<span id="cb28-4"><a></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb28-5"><a></a>       <span class="at">mu =</span> global_mean_satisfaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  wvs_cleaned$life_satisfaction
t = 15.476, df = 5101, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 6.5
95 percent confidence interval:
 6.881375 6.992008
sample estimates:
mean of x 
 6.936691 </code></pre>
</div>
</div>
</section>
<section id="reporting-t-in-apa-style-one-sample" class="slide level2">
<h2>Reporting t in APA style (one-sample)</h2>
<p><span class="math display">\[t(5101) = 15.48,\ p &lt; .001\]</span></p>
<p>Good practice is to also state the sample mean and the value it was compared against, e.g.&nbsp;the sample mean (<em>M</em> = 6.94) was significantly higher than the global average of 6.5.</p>
</section>
<section id="learning-check-2" class="slide level2">
<h2>Learning Check #2</h2>
<p>Look at the following data from <code>CO2</code>. Walk the map: <code>Treatment</code> is categorical with <strong>2</strong> groups, <code>uptake</code> is continuous — so which t-test compares the CO₂ <code>uptake</code> between the two treatments?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">summary</span>(CO2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Plant             Type         Treatment       conc          uptake     
 Qn1    : 7   Quebec     :42   nonchilled:42   Min.   :  95   Min.   : 7.70  
 Qn2    : 7   Mississippi:42   chilled   :42   1st Qu.: 175   1st Qu.:17.90  
 Qn3    : 7                                    Median : 350   Median :28.30  
 Qc1    : 7                                    Mean   : 435   Mean   :27.21  
 Qc3    : 7                                    3rd Qu.: 675   3rd Qu.:37.12  
 Qc2    : 7                                    Max.   :1000   Max.   :45.50  
 (Other):42                                                                  </code></pre>
</div>
</div>
</section></section>
<section>
<section id="categorical-3-groups-continuous-anova" class="title-slide slide level1 center">
<h1>Categorical (3+ groups) + continuous → ANOVA</h1>

</section>
<section id="where-we-are-right-now-3" class="slide level2">
<h2>Where we are right now</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Y</th>
<th>X</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td>Chi-square</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Continuous</td>
<td>Correlation</td>
</tr>
<tr class="odd">
<td>Continuous</td>
<td>Categorical (2)</td>
<td>t-test</td>
</tr>
<tr class="even">
<td><strong>Continuous</strong></td>
<td><strong>Categorical (3+)</strong></td>
<td>← <strong>ANOVA</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>You may not have met ANOVA in your stats class yet, but that’s fine! We can explore this together; IRL, you may run into this very often, as it’s the tool for <strong>“comparing means across 3 or more groups”.</strong> A t-test only handles two.</p>
</div>
</div>
</div>
</section>
<section id="anova-analysis-of-variance" class="slide level2">
<h2>ANOVA (Analysis of Variance)</h2>
<p>ANOVA (Analysis of Variance) is a statistical test used to compare the means of three or more groups or samples and determine if the differences are statistically significant.</p>
<p>There are two ‘mainstream’ ANOVA:</p>
<ul>
<li class="fragment"><strong>One-Way ANOVA</strong>: comparing means across two or more independent groups (levels) of a <u><strong>single</strong></u> independent variable.</li>
<li class="fragment"><strong>Two-Way ANOVA</strong>: comparing means across groups defined by <u><strong>two</strong></u> independent variables. <em>(we’ll cover this in the appendix if time allows)</em></li>
<li class="fragment">Other types of ANOVA that you may encounter: Repeated measures ANOVA, Multivariate ANOVA (MANOVA), ANCOVA, etc.</li>
</ul>
</section>
<section id="one-way-anova-sample-problem-and-result" class="slide level2">
<h2>One-Way ANOVA: Sample problem and result</h2>
<p>RQ: <strong>Is there a significant difference in emancipative values between different countries?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(H_0\)</span>: All countries have the <strong>same</strong> mean emancipative values (<span class="math inline">\(\mu_1 = \mu_2 = \dots = \mu_k\)</span>).</p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(H_1\)</span>: <strong>At least one</strong> country’s mean differs from the others.</p>
</div></div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note the <span class="math inline">\(H_1\)</span> — ANOVA only tells you <em>at least one</em> group stands out, <strong>not which one(s)</strong>. That’s what the post-hoc test is for, later.</p>
</div>
</div>
</div>
<p>Let’s visualize the data first!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> country, <span class="at">y =</span> emancipative_values)) <span class="sc">+</span></span>
<span id="cb32-3"><a></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-5"><a></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="one-way-anova-sample-problem-and-result-output" class="slide level2 output-location-slide"><h2>One-Way ANOVA: Sample problem and result</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-19-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="conduct-the-one-way-anova-test" class="slide level2">
<h2>Conduct the one-way Anova test</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>emanc_country_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(emancipative_values <span class="sc">~</span> country, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb33-2"><a></a><span class="fu">summary</span>(emanc_country_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
country        3  19.90   6.633     360 &lt;2e-16 ***
Residuals   5098  93.94   0.018                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div style="font-size: 75%; width: 75%">
<ul>
<li><strong>F-value</strong>: the coefficient value</li>
<li><strong>Pr(&gt;F)</strong>: the p-value</li>
<li><strong>Sum Sq</strong>: Sum of Squares</li>
<li><strong>Mean Sq</strong> : Mean Squares</li>
<li><strong>Df</strong>: Degrees of Freedom</li>
</ul>
</div>
<p>The p-value is tiny — so there <em>is</em> a significant difference somewhere.</p>
</section>
<section id="reporting-f-in-apa-style" class="slide level2">
<h2>Reporting F in APA style</h2>
<p>Cite F with <strong>both</strong> degrees of freedom (the <code>country</code> df, then the <code>Residuals</code> df), the F value, and the p-value:</p>
<p><span class="math display">\[F(3,\ 5098) = 360.00,\ p &lt; .001\]</span></p>
<ul>
<li>The numerator df (3) is from the <code>country</code> row, the denominator df (5098) from the <code>Residuals</code> row</li>
<li>Write <code>p &lt; .001</code> rather than R’s <code>&lt;2e-16</code></li>
</ul>
</section>
<section id="side-track-what-is-the-f-statistic" class="slide level2">
<h2>Side track: what <em>is</em> the F statistic?</h2>
<p>The F statistic is a <strong>ratio of two variances</strong>: how much the group means differ from each other, versus how much scores vary <em>within</em> the groups.</p>
<p><span class="math display">\[F = \frac{\text{variance }between\text{ groups}}{\text{variance }within\text{ groups}} = \frac{\text{signal}}{\text{noise}}\]</span></p>
<ul>
<li><strong>Big F</strong> → the gaps between country means are large compared to the random noise inside each country; this means it’s likely a <em>real</em> difference.</li>
<li><strong>F near 1</strong> → the between-group gaps are no bigger than the ordinary variation you’d expect by chance; this means probably no real difference.</li>
<li>This is literally why it’s called <strong>Analysis of <em>Variance</em> </strong>, because we compare means <em>by comparing variances</em>.</li>
</ul>
</section>
<section id="why-report-f-and-not-just-p-value" class="slide level2">
<h2>Why report F (and not just p-value)?</h2>
<p>The p-value alone tells the reader almost nothing on its own. Reporting the full <span class="math inline">\(F(df_1, df_2) = \dots,\ p\)</span> lets a reader:</p>
<ul>
<li><strong>See the test and its scale.</strong> F with its two df says <em>which</em> test you ran and how big the effect is relative to the noise, not just that <span class="math inline">\(p &lt; .05\)</span>.</li>
<li><strong>Judge the sample.</strong> The degrees of freedom encode the number of groups and the sample size. A significant result on 5,000 rows will be a very different claim than one on 30.</li>
<li><strong>Reproduce and verify.</strong> Anyone can recompute p from <span class="math inline">\(F\)</span> and the df, or compare your result to others.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Same idea as the t-test: report the <em>statistic</em>, its <em>df</em>, and <em>p</em> together — never the p-value in isolation.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="anova---checking-assumptions" class="title-slide slide level1 center">
<h1>ANOVA - Checking assumptions</h1>

</section>
<section id="this-part-is-your-job-not-the-ais" class="slide level2">
<h2>This part is <em>your</em> job, not the AI’s</h2>
<p>But before we trust it — <strong>was this even the appropriate test for our data?</strong> An ANOVA will <strong>always</strong> give you an F-value and a p-value, even when it’s the wrong approach for your data. R won’t stop you, and Claude/ChatGPT certainly won’t stop you either.</p>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>When and where possible, check the assumptions every time.</strong></p>
</div>
</div>
</div>
<p>Checking the assumptions is the human’s job. For ANOVA, the main things to verify:</p>
<ul>
<li>The DV is continuous; the IV is categorical ✅ (we chose it that way)</li>
<li>Observations are independent</li>
<li>The model <strong>residuals</strong> are approximately <strong>normal</strong> — note: the residuals, <em>not</em> the raw DV → <em>Q-Q plot, Shapiro-Wilk test</em></li>
<li>The groups have roughly <strong>equal variance</strong> (homoskedasticity) → <em>Levene’s test</em></li>
<li>No severe outliers</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>“Check” doesn’t mean “run a test and obey the p-value” — it means <em>look</em> at your data and <em>understand</em> what the test needs. We’ll see why that distinction matters in a moment.</p>
</div>
</div>
</div>
</section>
<section id="checking-normality-shapiro-wilk-test" class="slide level2 scrollable">
<h2>Checking normality: Shapiro-Wilk Test</h2>
<p><strong>Shapiro-Wilk Test</strong> checks normality. <span class="math inline">\(H_0\)</span> = the residuals are normally distributed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># so it samples the same way every time</span></span>
<span id="cb35-2"><a></a><span class="fu">shapiro.test</span>(<span class="fu">sample</span>(<span class="fu">residuals</span>(emanc_country_anova), <span class="dv">5000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sample(residuals(emanc_country_anova), 5000)
W = 0.99354, p-value = 2.908e-14</code></pre>
</div>
</div>
<p>The p-value is below 0.05, so <em>technically</em> the residuals aren’t perfectly normal.</p>
</section>
<section id="limitations-of-shapiro-wilk-test" class="slide level2">
<h2>Limitations of Shapiro-Wilk test</h2>
<p>Worth <strong>understanding rather than obeying</strong> — Shapiro-Wilk has a well-known limitation with large datasets:</p>
<ul>
<li><strong>It’s highly sensitive to sample size.</strong> As <span class="math inline">\(n\)</span> grows, the test’s statistical power climbs so high that it flags tiny, practically irrelevant deviations as “significant”. At ~5,000 rows it will reject normality almost every time.</li>
<li><strong>No real-world data is <em>perfectly</em> normal.</strong> So at this size the test is mostly detecting that unavoidable imperfection — not a problem that actually threatens your ANOVA.</li>
<li><strong>R even caps <code>shapiro.test()</code> at 5,000 observations</strong> (that’s why we had to <code>sample()</code> down just to run it). It isn’t built for big dataset.</li>
</ul>
<p>Even though technically this means “assumption failed”, we can treat this as a cue to <em>look</em> at the data instead.</p>
</section>
<section id="checking-normality-visually-q-q-plot" class="slide level2">
<h2>Checking normality visually: Q-Q Plot</h2>
<p>For normality, the visualisation is more helpful, <em>especially</em> at large n, where Shapiro-Wilk over-reacts. If the points hug the diagonal, the residuals are roughly normal. Ours drift off at the tails — but we can decide: <strong>is that drift severe, or cosmetic?</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">plot</span>(emanc_country_anova, <span class="dv">2</span>) <span class="co"># 2 is the number for Q-Q plot for ANOVA object's plot() function.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-22-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="better-ways-to-judge-normality-at-large-n" class="slide level2">
<h2>Better ways to judge normality at large n</h2>
<p>With a big sample, lean on <em>description and pictures</em> rather than the hypothesis test:</p>
<ul>
<li><strong>Q-Q plot</strong> (previous slide) — do the points roughly follow the diagonal? Minor wiggles at the tails are usually harmless.</li>
<li><strong>Histogram</strong> — is the overall shape roughly bell-like?</li>
<li><strong>Skewness &amp; kurtosis</strong> — quick numbers for asymmetry and “peakedness”. A common rule of thumb: values roughly between <strong>−2 and +2</strong> are acceptable for parametric tests like ANOVA.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>What’s a Q-Q plot?</strong> It compares your residuals against what a <em>perfect</em> normal distribution would look like: your sorted values on the y-axis, the values a normal distribution expects on the x-axis. If the residuals are normal, the points fall along the diagonal line. Curves or points drifting off at the <strong>tails</strong> (top-right / bottom-left) flag departures from normality — but unlike Shapiro-Wilk, the plot lets you <em>see how big</em> the departure actually is instead of just getting a pass/fail p-value.</p>
</div>
</div>
</div>
</section>
<section id="check-for-skewness-and-kurtosis" class="slide level2">
<h2>Check for skewness and kurtosis</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a><span class="fu">library</span>(moments)</span>
<span id="cb38-2"><a></a></span>
<span id="cb38-3"><a></a>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(emanc_country_anova) <span class="co"># get just the residuals</span></span>
<span id="cb38-4"><a></a><span class="fu">skewness</span>(resid)       <span class="co"># ~0 = symmetric</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3277311</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">library</span>(moments)</span>
<span id="cb40-2"><a></a></span>
<span id="cb40-3"><a></a>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(emanc_country_anova) <span class="co"># get just the residuals</span></span>
<span id="cb40-4"><a></a><span class="fu">kurtosis</span>(resid) <span class="sc">-</span> <span class="dv">3</span>   <span class="co"># "excess" kurtosis; ~0 = normal-ish</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07103331</code></pre>
</div>
</div>
<p>Check whether these land inside the ±2 rule of thumb — if they do, that’s a good sign the earlier Shapiro-Wilk “failure” was the test over-reacting, not a real problem.</p>
</section>
<section id="checking-equal-variance-levenes-test" class="slide level2">
<h2>Checking equal variance: Levene’s Test</h2>
<p><strong>Levene’s Test</strong> checks homogeneity of variance (homoskedasticity).</p>
<p><span class="math inline">\(H_0\)</span> = variances are equal across groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">library</span>(car)</span>
<span id="cb42-2"><a></a><span class="fu">leveneTest</span>(emancipative_values <span class="sc">~</span> country,</span>
<span id="cb42-3"><a></a>           <span class="at">data =</span> wvs_cleaned)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
        Df F value    Pr(&gt;F)    
group    3  28.818 &lt; 2.2e-16 ***
      5098                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="checking-equal-variance-levenes-test---result" class="slide level2">
<h2>Checking equal variance: Levene’s Test - result</h2>
<p>The p-value is below 0.05, which means the variances across our comparison groups are significantly different. However, the same large-sample limitation applies as with Shapiro-Wilk:</p>
<ul>
<li><strong>Massive statistical power at n ≈ 5,000.</strong> Levene’s test will flag a microscopic, trivial difference in spread as “significant”, even when it’s far too small to affect your ANOVA.</li>
<li><strong>Statistical ≠ practical significance.</strong> A low p-value says a difference <em>exists</em> in the population — not that it <em>matters</em>. In big datasets, the two often come apart completely.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>So pair the test with the <strong>boxplot from earlier</strong> and ask: the p-value says the variances differ, but do the boxes look <em>radically</em> different, or basically the same? If they look similar, you can safely proceed.</p>
</div>
</div>
</div>
</section>
<section id="judging-equal-variance-at-large-n---strategy-1" class="slide level2">
<h2>Judging equal variance at large n - Strategy #1</h2>
<p>Two calmer strategies than agonising over Levene’s p-value:</p>
<p><strong>1. Remember ANOVA and t-tests are robust.</strong> They tolerate <em>minor</em> unequal variances well, especially when group sizes are roughly equal. A common rule of thumb: if the <strong>largest group variance ÷ the smallest is ≤ about 4</strong> (with similar <span class="math inline">\(n\)</span>), the violation is generally harmless.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a></a>    <span class="fu">group_by</span>(country) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a></a>    <span class="fu">summarise</span>(<span class="at">variance =</span> <span class="fu">var</span>(emancipative_values)) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a></a>    <span class="fu">arrange</span>(variance)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  country       variance
  &lt;fct&gt;            &lt;dbl&gt;
1 Indonesia       0.0131
2 Malaysia        0.0187
3 Turkey          0.0202
4 Hong Kong SAR   0.0219</code></pre>
</div>
</div>
<p>Compare the largest and smallest — is the ratio under ~4?</p>
</section>
<section id="judging-equal-variance-at-large-n---strategy-2" class="slide level2">
<h2>Judging equal variance at large n - Strategy #2</h2>
<p><strong>2. Or sidestep the assumption entirely</strong> — use a method that doesn’t require equal variances:</p>
<ul>
<li><strong>Welch’s t-test</strong> instead of Student’s (it’s already R’s default!)</li>
<li><strong>Welch’s ANOVA</strong> — <code>oneway.test(..., var.equal = FALSE)</code> — instead of standard ANOVA <em>(see appendix)</em>.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>The 4:1 variance-ratio figure is a widely-repeated rule of thumb — treat it as a rough guide, not a hard law. Different textbooks quote slightly different thresholds.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-look-shaky-now-what" class="slide level2">
<h2>Assumptions look shaky — now what?</h2>
<p>Levene flags possibly-unequal variance, and the Q-Q plot shows some non-normality. In real social-science data this is the <em>norm</em>, not the exception (human behaviour do be messy like that). A shaky assumption is a <strong>caution flag.</strong></p>
<p>And here we have a big cushion: with ~5,000 observations, the <strong>Central Limit Theorem</strong> makes the ANOVA F-test fairly robust to non-normality anyway. So we’re not obliged to panic. But when we <em>are</em> worried, we have two moves (often both):</p>
<ol type="1">
<li><strong>Choose another method</strong> — use a test that doesn’t lean on those assumptions.</li>
<li><strong>Disclose the limitation</strong> — say plainly what was shaky when you report.</li>
</ol>
</section>
<section id="sample-alternative-method-kruskal-wallis-rank-sum-test" class="slide level2">
<h2>Sample alternative method: Kruskal-Wallis rank sum test</h2>
<p>Alternative method: the <strong>Kruskal-Wallis rank sum test</strong> is the non-parametric alternative to one-way ANOVA — same question (“do the groups differ?”), no normality/equal-variance requirement:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="fu">kruskal.test</span>(emancipative_values <span class="sc">~</span> country, <span class="at">data =</span> wvs_cleaned)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  emancipative_values by country
Kruskal-Wallis chi-squared = 856.58, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="aside-even-the-experts-argue-about-this" class="slide level2">
<h2>Aside: even the experts argue about this</h2>
<p>Assumption-checking is less settled than a textbook makes it look. If you read working statisticians debate it, three tensions come up again and again:</p>
<ul>
<li><strong>Prediction vs inference.</strong> Assumptions matter <em>far</em> more when you’re inferring (our case today) than when you only care about predictive accuracy.</li>
<li><strong>Don’t over-test.</strong> Some argue that running a normality test and <em>then</em> choosing your main test based on the result actually distorts your error rates — you’re better off picking a robust method from the start than “testing your way” to one.</li>
<li><strong>Understand, don’t ritualise.</strong> Checking assumptions only helps if you understand <em>what</em> each test assumes and <em>why</em>. Don’t blindly run Shapiro-Wilk on 5,000 rows.</li>
</ul>
<p>IRL data is complicated; <strong>no rulebook (and no AI) removes the need for your judgement</strong> about whether a result can be trusted.</p>
</section>
<section id="the-discipline-remember-this-one" class="slide level2">
<h2>The discipline (remember this one)</h2>
<p>For every test you run (today’s and every one after) the same four steps:</p>
<ol type="1">
<li><strong>Define</strong> your research question and its variables. This will guide you in choosing the statistical test.</li>
<li><strong>Check</strong> — understand what the test assumes and judge whether it’s plausible (plots + sample size + common sense + advice from professor if needed).</li>
<li><strong>Adapt</strong> if there’s real cause for concern — e.g.&nbsp;a non-parametric alternative or a robust method.</li>
<li><strong>Disclose</strong> the limitation when you present, especially when real decisions is going to be made based on it — a class policy call, a client in your internship/workplace, your thesis committee.</li>
</ol>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>As one data scientist put it, “your conclusions are only as strong as the assumptions behind them” <em>(r/datascience)</em>. Steps 2–4 are exactly the part you can’t hand to an AI — it can generate the analysis, but it can’t be <em>accountable</em> for it. You can.</p>
</div>
</div>
</div>
</section>
<section id="which-groups-differ-post-hoc-test" class="slide level2">
<h2>Which groups differ? Post-hoc test</h2>
<p>A significant ANOVA/Kruskal-Wallis only says <em>“at least one group differs.”</em> To find out <em>which</em> country pairs drive it, we run a post-hoc test. <strong>Tukey’s HSD</strong> pairs with ANOVA:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">TukeyHSD</span>(emanc_country_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = emancipative_values ~ country, data = wvs_cleaned)

$country
                               diff         lwr         upr    p adj
Hong Kong SAR-Turkey     0.13688320  0.12289229  0.15087411 0.00e+00
Indonesia-Turkey        -0.02555210 -0.03946659 -0.01163760 1.44e-05
Malaysia-Turkey          0.05875724  0.04487350  0.07264098 0.00e+00
Indonesia-Hong Kong SAR -0.16243529 -0.17619055 -0.14868003 0.00e+00
Malaysia-Hong Kong SAR  -0.07812595 -0.09185011 -0.06440180 0.00e+00
Malaysia-Indonesia       0.08430934  0.07066310  0.09795558 0.00e+00</code></pre>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Strictly, when you fall back to Kruskal-Wallis the matching post-hoc is <strong>Dunn’s test</strong> (<code>FSA::dunnTest()</code>), not Tukey. For this workshop we’ll read Tukey to build intuition — but knowing <em>which</em> post-hoc matches <em>which</em> test is one example of the kind of judgement your prof might ask you to defend.</p>
</div>
</div>
</div>
</section></section>
<section id="recap" class="title-slide slide level1 center">
<h1>Recap</h1>
<ul>
<li><p>Start every analysis from the <strong>research question</strong>: read your variable types, then choose the test. That choice is something you must be able to <em>justify</em> — not outsource.</p></li>
<li><p><strong>Both categorical</strong> → <code>chisq.test()</code>, the <span class="math inline">\(X^2\)</span> test of independence.</p></li>
<li><p><strong>Both continuous</strong> → <code>cor.test()</code>, correlation (−1 to 1, 0 = none).</p></li>
<li><p><strong>Categorical (2 groups) + continuous</strong> → <code>t.test()</code>; three flavours: one-sample, independent, paired.</p></li>
<li><p><strong>Categorical (3+ groups) + continuous</strong> → <code>aov()</code>, ANOVA.</p></li>
<li><p>“Check” means <em>understanding</em> what a test assumes and judging whether it’s plausible (plots + sample size + sense), not blindly obeying a normality test — remember Shapiro-Wilk over-reacts on big samples. When there’s real cause for concern, adapt (e.g.&nbsp;<code>kruskal.test()</code>) and/or state the limitation plainly. This judgement is the part the AI can’t do for you — and the part you’re accountable for.</p></li>
</ul>
</section>

<section>
<section id="end-of-session-4" class="title-slide slide level1 center">
<h1>End of Session 4!</h1>
<p>Next session: Linear and Logistic Regressions</p>
</section>
<section id="quiz-time-compulsory" class="slide level2">
<h2>Quiz Time! (compulsory)</h2>
<p>Scan the QR Code below to assess your understanding of basic inferential statistics concepts in R, including variable types and common statistical tests. All questions are required and each is worth 1 mark.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="https://forms.cloud.microsoft/r/CSiySf1jmL"><img data-src="images/BasicInferentialStatsinRQRCode.png" class="quarto-figure quarto-figure-center" alt="Quiz QR Code: https://forms.cloud.microsoft/r/CSiySf1jmL" width="400"></a></p>
</figure>
</div>
<figcaption>Quiz QR Code: &lt;https://forms.cloud.microsoft/r/CSiySf1jmL&gt;</figcaption>
</figure>
</div>
</section></section>
<section>
<section id="appendix" class="title-slide slide level1 center">
<h1>Appendix</h1>
<ul>
<li>Two-Way ANOVA (if time allows)</li>
<li>More assumption diagnostics (Residual vs Fitted, Welch’s ANOVA)</li>
<li>Reporting with apaTables / gtsummary</li>
</ul>
</section>
<section id="two-way-anova-sample-problem-and-result" class="slide level2">
<h2>Two-Way ANOVA: Sample problem and result</h2>
<p>RQ: <strong>Is there a significant difference in emancipative values across education levels and countries?</strong></p>
<p>With two IVs, we test <strong>three</strong> null hypotheses at once (each with its own <span class="math inline">\(H_1\)</span>):</p>
<div style="font-size: 90%">
<ul>
<li><span class="math inline">\(H_0\)</span> (education): mean emancipative values are the <strong>same</strong> across education levels.</li>
<li><span class="math inline">\(H_0\)</span> (country): mean emancipative values are the <strong>same</strong> across countries.</li>
<li><span class="math inline">\(H_0\)</span> (interaction): the effect of education on emancipative values <strong>does not depend</strong> on country (no interaction).</li>
</ul>
</div>
<p>Let’s visualize the data!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> emancipative_values)) <span class="sc">+</span></span>
<span id="cb50-3"><a></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb50-4"><a></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> country) <span class="sc">+</span></span>
<span id="cb50-5"><a></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb50-6"><a></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="two-way-anova-sample-problem-and-result-output" class="slide level2 output-location-slide"><h2>Two-Way ANOVA: Sample problem and result</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-29-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="conduct-the-two-way-anova-test-additive-model" class="slide level2">
<h2>Conduct the Two-way ANOVA test (Additive model)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>emanc_edu_country_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(emancipative_values <span class="sc">~</span> education <span class="sc">+</span> country,</span>
<span id="cb51-2"><a></a>                               <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb51-3"><a></a><span class="fu">summary</span>(emanc_edu_country_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
education      2   8.14   4.068   226.2 &lt;2e-16 ***
country        3  14.06   4.685   260.5 &lt;2e-16 ***
Residuals   5096  91.65   0.018                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="post-hoc-test-for-two-way-anova" class="slide level2">
<h2>Post-hoc test for Two-way ANOVA</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">TukeyHSD</span>(emanc_edu_country_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = emancipative_values ~ education + country, data = wvs_cleaned)

$education
                    diff        lwr        upr p adj
Middle-Lower  0.04773565 0.03734686 0.05812444     0
Higher-Lower  0.09886157 0.08781877 0.10990437     0
Higher-Middle 0.05112592 0.03899222 0.06325962     0

$country
                               diff         lwr         upr     p adj
Hong Kong SAR-Turkey     0.10822841  0.09440647  0.12205035 0.0000000
Indonesia-Turkey        -0.02049669 -0.03424313 -0.00675025 0.0007425
Malaysia-Turkey          0.05083463  0.03711857  0.06455069 0.0000000
Indonesia-Hong Kong SAR -0.12872510 -0.14231423 -0.11513596 0.0000000
Malaysia-Hong Kong SAR  -0.05739378 -0.07095218 -0.04383537 0.0000000
Malaysia-Indonesia       0.07133132  0.05784989  0.08481275 0.0000000</code></pre>
</div>
</div>
</section>
<section id="conduct-the-two-way-anova-test-with-interaction" class="slide level2">
<h2>Conduct the Two-way ANOVA test (with Interaction)</h2>
<p>“With interaction” means we are testing whether the effect of one variable (education) on the outcome (emancipative values) depends on the level of the other variable (country), or vice versa. For the R code, we use <code>education * country</code> instead of <code>education + country</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a>emanc_edu_country_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(emancipative_values <span class="sc">~</span> education <span class="sc">*</span> country,</span>
<span id="cb55-2"><a></a>                               <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb55-3"><a></a><span class="fu">summary</span>(emanc_edu_country_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
education            2   8.14   4.068 228.569  &lt; 2e-16 ***
country              3  14.06   4.685 263.265  &lt; 2e-16 ***
education:country    6   1.06   0.177   9.955 5.94e-11 ***
Residuals         5090  90.58   0.018                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interaction-plot" class="slide level2">
<h2>Interaction plot</h2>
<p>To better see this effect, let’s plot the interaction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> emancipative_values,</span>
<span id="cb57-3"><a></a>                          <span class="at">group =</span> country, <span class="at">color =</span> country)) <span class="sc">+</span> <span class="co"># lines will be grouped and colored by country</span></span>
<span id="cb57-4"><a></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span> <span class="co"># Add points to show mean emancipative_values for each education level by country</span></span>
<span id="cb57-5"><a></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>) <span class="sc">+</span> <span class="co"># Connect the points with lines</span></span>
<span id="cb57-6"><a></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="interaction-plot-output" class="slide level2 output-location-slide"><h2>Interaction plot</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-33-1.png" width="1344"></p>
</figure>
</div>
</div>
</div></section><section id="interpreting-our-interaction-plot" class="slide level2">
<h2>Interpreting our interaction plot</h2>
<p>Some observations that we can make:</p>
<ul>
<li>Look at whether the lines for each country run roughly parallel — if they do, there is little interaction between education and country.</li>
<li>If the lines cross or diverge, this suggests the effect of education on emancipative values differs across countries.</li>
<li>Pay attention to which country shows the steepest slope — this indicates the strongest relationship between education level and emancipative values in that country.</li>
</ul>
</section>
<section id="more-diagnostics-residual-vs-fitted" class="slide level2">
<h2>More diagnostics: Residual vs Fitted</h2>
<p>When we plot the residuals<sup>1</sup>, we can see some outliers as well:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a></a><span class="fu">plot</span>(emanc_country_anova, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="04-stats_files/figure-revealjs/unnamed-chunk-34-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Residual = difference between an observed value and the mean of all values for that group.</p></li></ol></aside></section>
<section id="when-homoskedasticity-fails-welchs-anova" class="slide level2">
<h2>When homoskedasticity fails: Welch’s ANOVA</h2>
<p>Besides Kruskal-Wallis, <strong>Welch’s ANOVA</strong> is an alternative for when only the equal-variance assumption is violated (but normality is roughly OK):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a><span class="fu">oneway.test</span>(emancipative_values <span class="sc">~</span> country, <span class="at">data =</span> wvs_cleaned, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One-way analysis of means (not assuming equal variances)

data:  emancipative_values and country
F = 359.64, num df = 3.0, denom df = 2806.7, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="reporting-with-apatables" class="slide level2">
<h2>Reporting with apaTables</h2>
<p><code>apaTables</code> generates APA-formatted report tables for correlation, ANOVA, and regression. Limited customisation. The online docs are for the development version, so lean on the vignette. <a href="https://dstanley4.github.io/apaTables/index.html"><strong>Documentation here</strong></a></p>
<p>Example: correlation table for <code>political_scale</code>, <code>life_satisfaction</code>, and <code>financial_satisfaction</code></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="fu">library</span>(apaTables)</span>
<span id="cb61-2"><a></a></span>
<span id="cb61-3"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a></a>    <span class="fu">select</span>(life_satisfaction, financial_satisfaction, freedom_of_choice) <span class="sc">|&gt;</span></span>
<span id="cb61-5"><a></a>    <span class="fu">apa.cor.table</span>( <span class="at">table.number =</span> <span class="dv">1</span>, <span class="at">filename =</span> <span class="st">"fig-output/table-cor.doc"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="reporting-with-gtsummary" class="slide level2">
<h2>Reporting with gtsummary</h2>
<p><code>gt</code> (“great tables”) and its add-on <code>gtsummary</code> offer lots of customisation with good docs. <a href="https://www.danieldsjoberg.com/gtsummary/index.html"><strong>Documentation here</strong></a></p>
<p>Example: mean-differences table grouped by <code>sex</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb62-2"><a></a></span>
<span id="cb62-3"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb62-4"><a></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(life_satisfaction, financial_satisfaction, freedom_of_choice, sex) <span class="sc">|&gt;</span></span>
<span id="cb62-5"><a></a>    <span class="fu">tbl_summary</span>(<span class="at">by =</span> sex) <span class="sc">|&gt;</span></span>
<span id="cb62-6"><a></a>    <span class="fu">add_difference</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="reporting-with-gtsummary-output" class="slide level2 output-location-slide"><h2>Reporting with gtsummary</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div id="rjlkfkissb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rjlkfkissb table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rjlkfkissb thead, #rjlkfkissb tbody, #rjlkfkissb tfoot, #rjlkfkissb tr, #rjlkfkissb td, #rjlkfkissb th {
  border-style: none;
}

#rjlkfkissb p {
  margin: 0;
  padding: 0;
}

#rjlkfkissb .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rjlkfkissb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rjlkfkissb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rjlkfkissb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rjlkfkissb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rjlkfkissb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rjlkfkissb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rjlkfkissb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rjlkfkissb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rjlkfkissb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rjlkfkissb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rjlkfkissb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rjlkfkissb .gt_spanner_row {
  border-bottom-style: hidden;
}

#rjlkfkissb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rjlkfkissb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rjlkfkissb .gt_from_md > :first-child {
  margin-top: 0;
}

#rjlkfkissb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rjlkfkissb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rjlkfkissb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rjlkfkissb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rjlkfkissb .gt_row_group_first td {
  border-top-width: 2px;
}

#rjlkfkissb .gt_row_group_first th {
  border-top-width: 2px;
}

#rjlkfkissb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjlkfkissb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rjlkfkissb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rjlkfkissb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rjlkfkissb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjlkfkissb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rjlkfkissb .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rjlkfkissb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rjlkfkissb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rjlkfkissb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rjlkfkissb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjlkfkissb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rjlkfkissb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjlkfkissb .gt_left {
  text-align: left;
}

#rjlkfkissb .gt_center {
  text-align: center;
}

#rjlkfkissb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rjlkfkissb .gt_font_normal {
  font-weight: normal;
}

#rjlkfkissb .gt_font_bold {
  font-weight: bold;
}

#rjlkfkissb .gt_font_italic {
  font-style: italic;
}

#rjlkfkissb .gt_super {
  font-size: 65%;
}

#rjlkfkissb .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rjlkfkissb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rjlkfkissb .gt_indent_1 {
  text-indent: 5px;
}

#rjlkfkissb .gt_indent_2 {
  text-indent: 10px;
}

#rjlkfkissb .gt_indent_3 {
  text-indent: 15px;
}

#rjlkfkissb .gt_indent_4 {
  text-indent: 20px;
}

#rjlkfkissb .gt_indent_5 {
  text-indent: 25px;
}

#rjlkfkissb .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#rjlkfkissb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" style="width:100%;" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Male</strong><br>
N = 2,431<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Female</strong><br>
N = 2,671<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Difference</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">life_satisfaction</td>
<td class="gt_row gt_center" headers="stat_1">7.00 (6.00, 8.00)</td>
<td class="gt_row gt_center" headers="stat_2">7.00 (6.00, 8.00)</td>
<td class="gt_row gt_center" headers="estimate">-0.22</td>
<td class="gt_row gt_center" headers="conf.low">-0.33, -0.11</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">financial_satisfaction</td>
<td class="gt_row gt_center" headers="stat_1">6.00 (5.00, 8.00)</td>
<td class="gt_row gt_center" headers="stat_2">7.00 (5.00, 8.00)</td>
<td class="gt_row gt_center" headers="estimate">-0.15</td>
<td class="gt_row gt_center" headers="conf.low">-0.27, -0.03</td>
<td class="gt_row gt_center" headers="p.value">0.014</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">freedom_of_choice</td>
<td class="gt_row gt_center" headers="stat_1">7.00 (6.00, 8.00)</td>
<td class="gt_row gt_center" headers="stat_2">7.00 (6.00, 9.00)</td>
<td class="gt_row gt_center" headers="estimate">-0.13</td>
<td class="gt_row gt_center" headers="conf.low">-0.25, -0.01</td>
<td class="gt_row gt_center" headers="p.value">0.033</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="6" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Median (Q1, Q3)</td>
</tr>
<tr class="gt_footnotes even">
<td colspan="6" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Welch Two Sample t-test</td>
</tr>
<tr class="gt_sourcenotes odd">
<td colspan="6" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div></section><section id="exercise-for-two-way-anova" class="slide level2">
<h2>Exercise for Two-Way ANOVA</h2>
<p>Is there a significant difference in freedom of choice between different age groups?</p>
<ul>
<li>Visualize the data as well</li>
<li>Test for normality and homoskedasticity, and choose the appropriate test</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Show answer</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a>freedom_age_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(freedom_of_choice <span class="sc">~</span> age_group, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb63-2"><a></a><span class="fu">summary</span>(freedom_age_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)  
age_group      3     31  10.397   2.288 0.0765 .
Residuals   5098  23169   4.545                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>TukeyHSD:</p>
<div class="cell">
<details class="code-fold">
<summary>Show answer</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a></a><span class="fu">TukeyHSD</span>(freedom_age_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = freedom_of_choice ~ age_group, data = wvs_cleaned)

$age_group
                    diff         lwr        upr     p adj
29-44-18-28 -0.008186981 -0.21087357 0.19449961 0.9995998
45-60-18-28 -0.170722366 -0.38100370 0.03955897 0.1576238
61+-18-28    0.019484044 -0.27334253 0.31231062 0.9982235
45-60-29-44 -0.162535385 -0.35112647 0.02605570 0.1193053
61+-29-44    0.027671025 -0.24999021 0.30533226 0.9941119
61+-45-60    0.190206410 -0.09304639 0.47345921 0.3103294</code></pre>
</div>
</div>


</section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/smu logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://smu-libraries.github.io/r-socsci/">Introductory R for Social Science</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/smu-libraries\.github\.io\/r-socsci\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>