<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Bella Ratmelia">
  <title>Introductory R for Social Sciences – Session 5: Regression and Presenting Your Result</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-49bde94825fa39fb910dd92406f11d8e.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Session 5: Regression and Presenting Your Result</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bella Ratmelia 
</div>
</div>
</div>

</section>
<section id="todays-outline" class="slide level2">
<h2>Today’s Outline</h2>
<p>Today extends Session 4’s map: now the <strong>type of your outcome</strong> picks your model.</p>
<ol type="1">
<li>Linear regression — for <strong>continuous</strong> outcomes
<ul>
<li>one continuous predictor</li>
<li>multiple continuous predictor</li>
<li>one categorical predictor</li>
</ul></li>
<li>Logistic regression — for <strong>binary</strong> (yes/no) outcomes
<ul>
<li>one continuous predictor</li>
<li>one categorical predictor</li>
</ul></li>
<li>Presenting &amp; reporting your results</li>
<li><em>(bonus)</em> Quarto show-and-tell</li>
</ol>
</section>
<section id="open-your-project" class="slide level2">
<h2>Open your project</h2>
<ol type="1">
<li><p>Go to the folder where you put your project for this workshop</p></li>
<li><p>Find a file with <code>.Rproj</code> extension - this is the R project file that holds all the information about your project.</p></li>
</ol>

<img data-src="images/locate-rproj-file.jpg" class="r-stretch"><ol start="3" type="1">
<li>Double click on the file. Rstudio should launch with your project loaded!</li>
</ol>
</section>
<section id="set-up-for-today" class="slide level2">
<h2>Set up for today</h2>
<p>Today’s main flow runs on <strong>tidyverse + huxtable</strong> (for result tables). <code>car</code> and <code>DescTools</code> (from Session 1) are each used once via the <code>car::</code> / <code>DescTools::</code> prefix.</p>
<ol type="1">
<li>Create a new R script called <code>session-5.R</code></li>
<li>Paste this in:</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(huxtable)   <span class="co"># for presenting regression tables</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><code>gtsummary</code> and <code>apaTables</code> produce prettier tables but have heavier dependencies — they’re <strong>optional</strong>, with examples in the appendix. <code>huxtable</code> is lighter, and it’s all we need today.</p>
</div>
</div>
</div>
</section>
<section id="load-our-data-for-today" class="slide level2">
<h2>Load our data for today!</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="co"># read the CSV with WVS data</span></span>
<span id="cb2-2"><a></a>wvs_cleaned <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data-output/wvs_cleaned_v1.csv"</span>)</span>
<span id="cb2-3"><a></a></span>
<span id="cb2-4"><a></a><span class="co"># Convert categorical variables to factors</span></span>
<span id="cb2-5"><a></a>columns_to_convert <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"sex"</span>, <span class="st">"marital_status"</span>, <span class="st">"urban_rural"</span>, <span class="st">"income_level"</span>, <span class="st">"education"</span>, <span class="st">"trust_people"</span>, <span class="st">"age_group"</span>)</span>
<span id="cb2-6"><a></a></span>
<span id="cb2-7"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span> </span>
<span id="cb2-8"><a></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(columns_to_convert), as_factor))</span>
<span id="cb2-9"><a></a></span>
<span id="cb2-10"><a></a><span class="co"># peek at the data, pay attention to the data types!</span></span>
<span id="cb2-11"><a></a><span class="fu">glimpse</span>(wvs_cleaned)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="from-tests-to-models" class="slide level2">
<h2>From tests to models</h2>
<p>Session 4 asked <em>“which test?”</em> from your variable types. Regression asks the same kind of question — now the <strong>outcome’s type</strong> picks your model:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Your outcome (Y)</th>
<th>Model</th>
<th>R function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Continuous</strong></td>
<td>Linear regression</td>
<td><code>lm()</code></td>
</tr>
<tr class="even">
<td><strong>Binary</strong> (yes/no)</td>
<td>Logistic regression</td>
<td><code>glm(..., family = binomial)</code></td>
</tr>
</tbody>
</table>
<p>Whatever the model, the core skill is the same: <strong>read one coefficient at a time, in the units of your outcome.</strong> If a predictor is categorical, its coefficient is the difference from a <strong>reference</strong> group.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>You already know the shape of this from school: <span class="math inline">\(y = mx + c\)</span>. Regression just adds <em>uncertainty</em> (are the slope and intercept real?) and <em>more predictors</em>.</p>
</div>
</div>
</div>
</section>
<section>
<section id="simple-linear-regression" class="title-slide slide level1 center">
<h1>Simple Linear Regression</h1>

</section>
<section id="simple-linear-regression-what-is-it" class="slide level2">
<h2>Simple Linear Regression: what is it?</h2>
<p><strong>Linear regression</strong> is a statistical method used to model the relationship between a dependent variable (outcome) and one or more independent variables (predictors) by fitting a linear equation to the observed data. The math formula looks like this:</p>
<div class="columns">
<div class="column" style="width:30%;">
<p><span class="math display">\[Y = \beta_0 + \beta_1X + \varepsilon\]</span></p>
</div><div class="column" style="font-size: 75%; width: 70%;">
<ul>
<li><span class="math inline">\(Y\)</span> - the dependent variable; <strong>must be continuous</strong></li>
<li><span class="math inline">\(X\)</span> - the independent variable (if there are more than one, there will be <span class="math inline">\(X_1\)</span> , <span class="math inline">\(X_2\)</span> , and so on. This can be ordinal, nominal, or continuous</li>
<li><span class="math inline">\(\beta_0\)</span> - the y-intercept. Represents the expected value of independent variable <span class="math inline">\(Y\)</span> when independent variable(s) <span class="math inline">\(X\)</span> are set to zero.</li>
<li><span class="math inline">\(\beta_1\)</span> - the slope / coefficient for independent variable</li>
<li><span class="math inline">\(\varepsilon\)</span> - the error term. (In some examples you might see this omitted from the formula).</li>
</ul>
</div></div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>This is the <span class="math inline">\(y = mx + c\)</span> line from secondary school, dressed up: <span class="math inline">\(\beta_0\)</span> is the intercept (<span class="math inline">\(c\)</span>), <span class="math inline">\(\beta_1\)</span> is the slope (<span class="math inline">\(m\)</span>). Regression’s job is to find the best-fitting <span class="math inline">\(m\)</span> and <span class="math inline">\(c\)</span> from your data — and tell you whether they’re statistically real.</p>
</div>
</div>
</div>
<p>Examples:</p>
<ul>
<li>Does a person’s <strong>secular values</strong> affect their <strong>life satisfaction</strong>?</li>
<li>Do a person’s <strong>secular values</strong> and <strong>financial satisfaction</strong> affect their <strong>life satisfaction</strong>?</li>
</ul>
</section>
<section id="linear-regression-one-continuous-predictor" class="slide level2">
<h2>Linear Regression: One continuous predictor</h2>
<p><strong>Research Question:</strong> Does a person’s level of <strong>secular values</strong> influence their <strong>life satisfaction</strong>?</p>
<ul>
<li>The outcome/DV (<span class="math inline">\(Y\)</span>): <code>life_satisfaction</code></li>
<li>The predictor/IV (<span class="math inline">\(X\)</span>): <code>secular_values</code></li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><code>secular_values</code> is Welzel’s secular-values index, ranging from <strong>0</strong> (very traditional/religious) to <strong>1</strong> (very secular). Keep this 0–1 scale in mind when interpreting the coefficient!</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>life_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_satisfaction <span class="sc">~</span> secular_values, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb3-2"><a></a><span class="fu">summary</span>(life_model1) <span class="co">#summarize the result</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell fragment">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_satisfaction ~ secular_values, data = wvs_cleaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.7641 -1.1920  0.2271  1.3497  4.0281 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     7.79792    0.06045     129   &lt;2e-16 ***
secular_values -2.43734    0.15230     -16   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.967 on 5100 degrees of freedom
Multiple R-squared:  0.04782,   Adjusted R-squared:  0.04763 
F-statistic: 256.1 on 1 and 5100 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div style="font-size: 80%">
<ul>
<li><p><strong>Call</strong>: the formula</p></li>
<li><p><strong>Residuals</strong>: overview on the distribution of residuals (expected value minus observed value) – we can plot this to check for homoscedasticity</p></li>
<li><p><strong>Coefficients</strong>: shows the intercept, the regression coefficients for the predictor variables, and their statistical significance</p></li>
<li><p><strong>Residual standard error</strong>: the average difference between observed and expected outcome by the model. Generally the lower, the better.</p></li>
<li><p><strong>R-squared &amp; Adjusted R-squared</strong>: indicates the proportion of variation in the outcome that can be explained by the model (i.e.&nbsp;goodness of fit).</p></li>
<li><p><strong>F-statistics</strong>: indicates whether the model as a whole is statistically significant and whether it explains more variance than just the baseline (intercept-only) model.</p></li>
</ul>
</div>
</section>
<section id="narrating-the-results" class="slide level2">
<h2>Narrating the results</h2>
<p>Here is one possible way to narrate your result:</p>
<blockquote>
<p>A linear regression analysis was conducted to assess the influence of secular values on life satisfaction in Hong Kong SAR, Indonesia, Malaysia, and Turkey. Secular values were a statistically significant, negative predictor of life satisfaction (B = -2.44, SE = 0.15, p &lt; 0.001).</p>
</blockquote>
<blockquote>
<p>Because <code>secular_values</code> ranges from 0 to 1, the raw coefficient describes the change across the <em>entire</em> scale. It is easier to interpret in smaller steps: for each <strong>0.1 increase</strong> in secular values, life satisfaction decreases by about <strong>0.24 units</strong> (−2.44 × 0.1) — that is, more secular respondents reported slightly lower life satisfaction.</p>
</blockquote>
<blockquote>
<p>The model was statistically significant (F(1, 5100) = 256.13, p &lt; 0.001) but explained only about 4.8% of the variance in life satisfaction (R² = 0.048).</p>
</blockquote>
</section>
<section id="linear-regression-multiple-continuous-predictors" class="slide level2">
<h2>Linear Regression: Multiple continuous predictors</h2>
<p><strong>Research Question:</strong> Do a person’s <strong>financial satisfaction</strong> and <strong>secular values</strong> affect their <strong>life satisfaction</strong>?</p>
<ul>
<li>The outcome/DV (<span class="math inline">\(Y\)</span>): <code>life_satisfaction</code></li>
<li>The predictors/IV (<span class="math inline">\(X\)</span>): <code>financial_satisfaction</code> and <code>secular_values</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>life_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_satisfaction <span class="sc">~</span> financial_satisfaction <span class="sc">+</span> secular_values,</span>
<span id="cb5-2"><a></a>                  <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb5-3"><a></a><span class="fu">summary</span>(life_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="linear-regression-multiple-continuous-predictors-output" class="slide level2 output-location-slide"><h2>Linear Regression: Multiple continuous predictors</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_satisfaction ~ financial_satisfaction + secular_values, 
    data = wvs_cleaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.5036 -0.8939  0.0305  0.8466  5.9702 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             4.36997    0.08547   51.13   &lt;2e-16 ***
financial_satisfaction  0.51588    0.01046   49.32   &lt;2e-16 ***
secular_values         -1.81378    0.12596  -14.40   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.619 on 5099 degrees of freedom
Multiple R-squared:  0.3554,    Adjusted R-squared:  0.3551 
F-statistic:  1405 on 2 and 5099 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></section><section id="possible-way-to-explain-the-result" class="slide level2">
<h2>Possible way to explain the result</h2>
<blockquote>
<p>A multiple regression analysis was conducted to examine how financial satisfaction and secular values predict life satisfaction. Financial satisfaction was a strong positive predictor (B = 0.52, SE = 0.01, p &lt; 0.001): for each one-unit increase in financial satisfaction (on the 1–10 scale), life satisfaction increased by about 0.52 units. Secular values were a significant negative predictor (B = -1.81, SE = 0.13, p &lt; 0.001); since this variable ranges 0–1, a 0.1 increase in secular values corresponds to about a 0.18-unit decrease in life satisfaction.</p>
</blockquote>
<blockquote>
<p>The model was statistically significant (F(2, 5099) = 1405.49, p &lt; 0.001) and explained about 35.5% of the variance in life satisfaction (R² = 0.355).</p>
</blockquote>
</section>
<section id="reporting-result-a-sample-regression-table" class="slide level2">
<h2>Reporting result: A sample regression table</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><img data-src="images/regression-table.jpg"></p>
</div><div class="column" style="width:40%;">
<p>You might encounter different table formats when reporting regression results, but there are some key elements that should generally be included.</p>
<p>These are: the number of observations (<span class="math inline">\(N\)</span>), the coefficients (B = unstandardized, raw coeff in original unit of measurements; <span class="math inline">\(\beta\)</span> = standardized, converted to standard deviation units), standard errors (SE), confidence intervals (95% CI), and p-values. Other metrics to include are the <span class="math inline">\(R^2\)</span> and <span class="math inline">\(F\)</span> statistics.</p>
</div></div>

<aside><div>
<ul>
<li>The above screenshot is taken from <a href="https://www.ncfr.org/system/files/2017-01/regression_0.pdf" class="uri">https://www.ncfr.org/system/files/2017-01/regression_0.pdf</a></li>
<li><a href="https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#regression">APA recommended format</a></li>
</ul>
</div></aside></section>
<section id="presenting-your-results-with-huxtable" class="slide level2 scrollable">
<h2>Presenting your results with huxtable</h2>
<p><code>huxreg()</code> turns one or more models into a clean, copy-pasteable table — put several side by side to compare them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">huxreg</span>(<span class="st">"model 1"</span> <span class="ot">=</span> life_model1, <span class="st">"model 2"</span> <span class="ot">=</span> life_model2,</span>
<span id="cb7-2"><a></a>       <span class="at">bold_signif =</span> <span class="fl">0.05</span>,</span>
<span id="cb7-3"><a></a>       <span class="at">statistics =</span> <span class="fu">c</span>(<span class="st">"R squared"</span> <span class="ot">=</span> <span class="st">"r.squared"</span>, <span class="st">"N"</span> <span class="ot">=</span> <span class="st">"nobs"</span>,</span>
<span id="cb7-4"><a></a>                      <span class="st">"F"</span> <span class="ot">=</span> <span class="st">"statistic"</span>, <span class="st">"P value"</span> <span class="ot">=</span> <span class="st">"p.value"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>For a single model, just <code>huxreg(life_model1)</code>. The table appears in RStudio’s <strong>Viewer</strong> pane — select it, copy (Ctrl/Cmd + C), and paste into Word or Google Docs.</p>
</div>
</div>
</div>
</section>
<section id="presenting-your-results-with-huxtable-output" class="slide level2 scrollable output-location-slide"><h2>Presenting your results with huxtable</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="margin-left: auto; margin-right: auto;">
<colgroup><col><col><col></colgroup><thead>
<tr>
<th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;"></th><th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;">model 1</th><th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;">model 2</th></tr>
</thead>
<tbody>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">(Intercept)</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;      font-weight: bold;">7.798 ***</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;      font-weight: bold;">4.370 ***</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">(0.060)&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">(0.085)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">secular_values</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">-2.437 ***</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">-1.814 ***</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">(0.152)&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">(0.126)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">financial_satisfaction</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: bold;">0.516 ***</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;      font-weight: bold;">(0.010)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">R squared</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">0.048&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">0.355&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">N</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">5102&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">5102&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">F</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">256.128&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">1405.492&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;      font-weight: normal;">P value</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" colspan="3" style="border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;">*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</th></tr>
</tbody>
</table>
</div>
</div></section><section id="fyi-multicollinearity" class="slide level2">
<h2>FYI: Multicollinearity</h2>
<p>Caution! When doing regression-type of tests, watch out for multicollinearity.</p>
<p>Multicollinearity is a situation in which two or more predictor variables are highly correlated with each other. This makes it difficult to determine the specific contribution of each predictor variable to the relationship.</p>
<p>One way to check for it:</p>
<ul>
<li><p>Assess the correlation between your predictor variables in your model using Variance Inflation Factor (VIF)</p></li>
<li><p>If they seem to be highly correlated (&gt; 5 or so), one of the easiest (and somewhat acceptable) way is to simply remove the less significant predictor from your model :D</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>car<span class="sc">::</span><span class="fu">vif</span>(life_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>financial_satisfaction         secular_values 
              1.010177               1.010177 </code></pre>
</div>
</div>
</section>
<section id="linear-regression-one-categorical-predictor" class="slide level2">
<h2>Linear Regression: One categorical predictor</h2>
<p><strong>Research Question</strong>: Explore the difference in life satisfaction between countries</p>
<ul>
<li>The outcome/DV (<span class="math inline">\(Y\)</span>): <code>life_satisfaction</code></li>
<li>The predictor/IV (<span class="math inline">\(X\)</span>): <code>country</code> — an <strong>unordered</strong> categorical variable (the countries have no inherent order)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Before proceeding with analysis, ensure that all the categorical variables involved are cast as factors! (We already did this in the load-data step.)</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="co"># country is already a factor from our load-data step — no ordering needed,</span></span>
<span id="cb10-2"><a></a><span class="co"># since it's a nominal (unordered) variable</span></span>
<span id="cb10-3"><a></a><span class="fu">str</span>(wvs_cleaned<span class="sc">$</span>life_satisfaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:5102] 8 10 4 1 9 10 8 5 8 5 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">str</span>(wvs_cleaned<span class="sc">$</span>country)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 4 levels "Turkey","Hong Kong SAR",..: 1 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
</section>
<section id="continuing-the-analysis" class="slide level2">
<h2>Continuing the analysis</h2>
<p>The analysis summary should look like this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>life_model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_satisfaction <span class="sc">~</span> country, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb14-2"><a></a><span class="fu">summary</span>(life_model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_satisfaction ~ country, data = wvs_cleaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.6311 -1.3544  0.3689  1.3876  3.5238 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           6.47615    0.05637 114.887  &lt; 2e-16 ***
countryHong Kong SAR  0.13627    0.07884   1.729    0.084 .  
countryIndonesia      1.15490    0.07841  14.730  &lt; 2e-16 ***
countryMalaysia       0.51319    0.07823   6.560 5.92e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.966 on 5098 degrees of freedom
Multiple R-squared:  0.04935,   Adjusted R-squared:  0.04879 
F-statistic: 88.22 on 3 and 5098 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>When interpreting a categorical predictor in regression, one category is treated as the reference category, which serves as the baseline for comparison. In this case, the reference category corresponds to the intercept.</p></li>
<li><p>By default, the first category in the data is used as the reference — here that’s <strong>Turkey</strong>, so each coefficient is a country’s difference from Turkey.</p></li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Sound familiar? This is the same comparison a <strong>one-way ANOVA</strong> makes (Session 4) — a one-way ANOVA <em>is</em> a linear regression with a single categorical predictor.</p>
</div>
</div>
</div>
</section>
<section id="narrating-the-result" class="slide level2">
<h2>Narrating the result</h2>
<p>Here is one possible way to narrate your result:</p>
<blockquote>
<p>A linear regression analysis was conducted to examine how country predicts life satisfaction, with <strong>Turkey as the reference group</strong> (intercept = 6.48, SE = 0.06). Compared to Turkey, respondents in Indonesia reported significantly higher life satisfaction (B = 1.15, SE = 0.08, p &lt; 0.001), as did those in Malaysia (B = 0.51, SE = 0.08, p &lt; 0.001). Hong Kong SAR scored slightly higher, but the difference was not statistically significant (B = 0.14, SE = 0.08, p = 0.084).</p>
</blockquote>
<blockquote>
<p>The model was statistically significant (F(3, 5098) = 88.22, p &lt; 0.001) but explained only about 4.9% of the variance in life satisfaction (R² = 0.049).</p>
</blockquote>
</section>
<section id="categorical-predictor-changing-the-reference" class="slide level2">
<h2>Categorical predictor: changing the reference</h2>
<p>Let’s change the reference category for <code>country</code> to “Malaysia” (our neighbour!).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a></a>    <span class="fu">mutate</span>(<span class="at">country =</span> <span class="fu">relevel</span>(country, <span class="at">ref =</span> <span class="st">"Malaysia"</span>))</span>
<span id="cb16-3"><a></a></span>
<span id="cb16-4"><a></a><span class="fu">str</span>(wvs_cleaned<span class="sc">$</span>country)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 4 levels "Malaysia","Turkey",..: 2 3 3 3 3 3 3 3 3 3 ...</code></pre>
</div>
</div>
<p>Re-run the analysis with the new reference category</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>life_model3a <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_satisfaction <span class="sc">~</span> country, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb18-2"><a></a><span class="fu">summary</span>(life_model3a)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="categorical-predictor-changing-the-reference-output" class="slide level2 output-location-slide"><h2>Categorical predictor: changing the reference</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_satisfaction ~ country, data = wvs_cleaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.6311 -1.3544  0.3689  1.3876  3.5238 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           6.98934    0.05425 128.842  &lt; 2e-16 ***
countryTurkey        -0.51319    0.07823  -6.560 5.92e-11 ***
countryHong Kong SAR -0.37692    0.07733  -4.874 1.13e-06 ***
countryIndonesia      0.64172    0.07689   8.345  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.966 on 5098 degrees of freedom
Multiple R-squared:  0.04935,   Adjusted R-squared:  0.04879 
F-statistic: 88.22 on 3 and 5098 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></section><section id="changing-baseline-category-for-ordered-factor" class="slide level2">
<h2>Changing baseline category for ordered factor</h2>
<p><code>income_level</code> is naturally <strong>ordered</strong>: <code>Low</code> &lt; <code>Medium</code> &lt; <code>High</code>. This is how we set (or change) that ordering explicitly as an ordered factor — put the levels in the sequence you want:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a></a>    <span class="fu">mutate</span>(<span class="at">income_level =</span> <span class="fu">factor</span>(income_level,</span>
<span id="cb20-3"><a></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>),</span>
<span id="cb20-4"><a></a>                         <span class="at">ordered =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div title="Ordered factors behave differently in regression">
<div class="callout callout-important callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ordered factors behave differently in regression</strong></p>
</div>
<div class="callout-content">
<p>This slide is about <strong>reordering the levels</strong> of an ordered factor. But be careful: an <strong>ordered</strong> factor doesn’t have a “reference category” the way an unordered one does. In a regression, R codes it with <strong>polynomial contrasts</strong> (you’ll see coefficients labelled <code>.L</code>, <code>.Q</code>, <code>.C</code> — linear/quadratic/cubic trends), <em>not</em> “difference from a baseline group”. So if you want the <strong>“difference from a reference group”</strong> interpretation we’ve been using, keep the factor <strong>unordered</strong> and just <code>relevel()</code> it (as we did for <code>country</code>).</p>
</div>
</div>
</div>
</div>
</section>
<section id="lets-try-this-linear-regression-exercise-5-mins" class="slide level2">
<h2>Let’s try this Linear Regression exercise! (5 mins)</h2>
<p>Create a regression model called <code>life_model4</code> that predicts the <code>life_satisfaction</code> score based on <code>sex</code>. The reference category should be ‘Male’</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>life_model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_satisfaction <span class="sc">~</span> sex, <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb21-2"><a></a><span class="fu">summary</span>(life_model4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_satisfaction ~ sex, data = wvs_cleaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.0416 -1.0416  0.1785  1.1785  3.1785 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.82147    0.04082 167.110  &lt; 2e-16 ***
sexFemale    0.22008    0.05642   3.901  9.7e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.013 on 5100 degrees of freedom
Multiple R-squared:  0.002975,  Adjusted R-squared:  0.00278 
F-statistic: 15.22 on 1 and 5100 DF,  p-value: 9.701e-05</code></pre>
</div>
</div>
</section>
<section id="wait-how-is-this-different-from-t-tests-and-anova" class="slide level2">
<h2>Wait — how is this different from t-tests and ANOVA?</h2>
<p><em>In case anyone’s been wondering the same thing!</em> You don’t need this to run any analysis today — it’s just the “why” for the curious. Here’s the intuition:</p>
<ul>
<li><strong>t-tests &amp; ANOVA</strong> are framed around <strong>comparing</strong> group means — <em>“are these groups different?”</em></li>
<li><strong>Correlation</strong> is framed around the <strong>strength &amp; direction of a relationship</strong> — <em>“do these two move together, and how tightly?”</em> (symmetric — no outcome vs.&nbsp;predictor)</li>
<li><strong>Regression</strong> is framed around <strong>predicting</strong> an outcome from predictors — <em>“what’s the relationship, and how big is it?”</em></li>
</ul>
<p>They all belong to the <strong>general linear model</strong> family; they differ mainly in the <em>types of variables</em> they take and the <em>question they’re framed around</em>. In fact, <strong>t-tests and ANOVA are special cases of linear regression</strong></p>
</section>
<section id="how-theyre-all-equivalent-to-regression" class="slide level2">
<h2>How they’re all equivalent to regression</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Traditional test</th>
<th>Equivalent regression</th>
<th>Gives the…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two-group t-test</td>
<td><code>lm(y ~ binary_group)</code></td>
<td>same <strong>p-value</strong></td>
</tr>
<tr class="even">
<td>One-way ANOVA</td>
<td><code>lm(y ~ multi_level_group)</code></td>
<td>same <strong>F-statistic &amp; p-value</strong></td>
</tr>
<tr class="odd">
<td>Correlation</td>
<td><code>lm(y ~ continuous_x)</code></td>
<td>same <strong>p-value</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>A traditional ANOVA runs an <em>omnibus</em> test — <em>“does <strong>any</strong> group differ?”</em> — so you need a post-hoc test (Tukey’s, from Session 4) to find out <em>which</em>. Regression instead hands you <strong>specific coefficients</strong>: each one is a group’s difference from the <strong>reference</strong> category, directly. The underlying math is roughly the same!</p>
</div>
</div>
</div>

<aside><div>
<p>Want to dig deeper? <a href="https://stats.stackexchange.com/questions/403517/t-test-anova-or-regression-whats-the-difference" target="_blank">This StackExchange thread</a> and StatQuest’s <a href="https://www.youtube.com/watch?v=NF5_btOaCig" target="_blank"><em>General Linear Models Pt. 2: t-tests and ANOVA</em></a> both explain why these are the same model.</p>
</div></aside></section>
<section id="so-which-one-should-i-use" class="slide level2">
<h2>So which one should I use?</h2>
<ul>
<li><strong>Any of them</strong> — pick the framing that fits your <strong>question</strong> and what your <strong>reader</strong> expects (many fields/professors expect a “t-test” or “ANOVA” for a group comparison).</li>
<li><strong>Regression</strong> is the most general, flexible member of the family: many predictors, continuous + categorical mixed, and interactions.</li>
<li>And <strong>logistic regression</strong> extends the very same idea to <em>binary</em> outcomes — which is exactly where we’re headed next.</li>
</ul>
</section></section>
<section>
<section id="binary-logistic-regression" class="title-slide slide level1 center">
<h1>Binary Logistic Regression</h1>

</section>
<section id="binary-logistic-regression---what-is-it" class="slide level2">
<h2>Binary Logistic Regression - what is it?</h2>
<p>Also known as simply logistic regression, it is used to model the relationship between a set of independent variables and a binary outcome.</p>
<p>These independent variables can be either categorical or continuous.</p>
<p>Binary Logistics Regression formula:</p>
<p><span class="math display">\[logit(P) = \beta_0 + \beta_1X_1 + \beta_2X_2 + … + \beta_nX_n\]</span></p>
<p>It can also be written like below, in which the <span class="math inline">\(logit(P)\)</span> part is expanded:</p>
<p><span class="math display">\[P = \frac{1}{1 + e^{-(\beta_0 + \beta_1X)}}\]</span></p>
<div title="The one-paragraph mental model">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The one-paragraph mental model</strong></p>
</div>
<div class="callout-content">
<p>The outcome is now <strong>yes/no</strong>. You can’t fit a straight line to a 0/1, so we model the <strong>log-odds</strong> instead — the intimidating <code>logit</code> and <span class="math inline">\(e^x\)</span> are just plumbing that keeps predicted probabilities between 0 and 1. What you actually <strong>read</strong> is the <strong>odds ratio</strong>: <strong>&gt;1</strong> = event more likely, <strong>&lt;1</strong> = less likely, for each 1-unit increase in X. If you hold onto just this, you’re set.</p>
</div>
</div>
</div>
</div>
</section>
<section id="binary-logistic-regression-examples" class="slide level2">
<h2>Binary Logistic Regression Examples</h2>
<ul>
<li>Does a person’s <strong>age</strong> and <strong>education level</strong> influence whether they will vote Democrat or Republican in the US election?</li>
<li>Does the number of <strong>hours spent studying</strong> impact a student’s likelihood of passing a module? (pass/fail outcome)</li>
</ul>
<p>In essence, the goal of binary logistic regression is to estimate the probability of a specific event happening when there are only two possible outcomes (hence the term “binary”).</p>
</section>
<section id="binary-logistic-regression-one-continuous-predictor" class="slide level2">
<h2>Binary Logistic Regression: One Continuous Predictor</h2>
<p><strong>Research Question</strong>: Does a participant’s <strong>sense of freedom of choice</strong> affect the likelihood of being satisfied with life?</p>
<ul>
<li><p>The outcome/DV (<span class="math inline">\(Y\)</span>): <code>satisfied</code></p>
<ul>
<li>Our outcome is a continuous variable, but for the purpose of this workshop practice, let’s define the outcome as “Satisfied” if the life_satisfaction score is more than 7 (inclusive), and “not Satisfied” if the score is less than 7.</li>
</ul></li>
<li><p>The predictor/IV (<span class="math inline">\(X\)</span>): <code>freedom_of_choice</code></p></li>
</ul>
</section>
<section id="dummy-coding-dependent-variable" class="slide level2">
<h2>Dummy-coding dependent variable</h2>
<p>Before we proceed with the calculations, we need to <strong>dummy code</strong> the dependent variable into 1 and 0, with 1 = Satisfied and 0 = Not Satisfied. <a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faqwhat-is-dummy-coding/">More info on dummy coding here</a></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="co"># First, we need to create a binary outcome</span></span>
<span id="cb23-2"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a></a>    <span class="fu">mutate</span>(<span class="at">satisfied =</span> <span class="fu">if_else</span>(life_satisfaction <span class="sc">&gt;=</span> <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb23-4"><a></a><span class="co"># the if_else is from dplyr package (from session 2)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,102 × 2
  life_satisfaction satisfied
              &lt;dbl&gt;     &lt;dbl&gt;
1                 8         1
2                10         1
3                 4         0
4                 1         0
5                 9         1
# ℹ 5,097 more rows</code></pre>
</div>
</div>
</section>
<section id="conduct-the-analysis" class="slide level2">
<h2>Conduct the analysis</h2>
<p>Let’s conduct the analysis!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>life_model5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(satisfied <span class="sc">~</span> freedom_of_choice,</span>
<span id="cb25-2"><a></a>                <span class="at">family =</span> binomial,</span>
<span id="cb25-3"><a></a>                <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb25-4"><a></a></span>
<span id="cb25-5"><a></a><span class="fu">summary</span>(life_model5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = satisfied ~ freedom_of_choice, family = binomial, 
    data = wvs_cleaned)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -2.60780    0.12024  -21.69   &lt;2e-16 ***
freedom_of_choice  0.45612    0.01714   26.62   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6739.0  on 5101  degrees of freedom
Residual deviance: 5832.1  on 5100  degrees of freedom
AIC: 5836.1

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
</section>
<section id="exponentiate-the-coefficients" class="slide level2">
<h2>Exponentiate the coefficients</h2>
<p>If you recall the formula, the results are expressed in Logit Probability. As we typically report the result in terms of Odd Ratios (OR), perform exponentiation on the coefficients.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="fu">exp</span>(<span class="fu">coef</span>(life_model5))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept) freedom_of_choice 
       0.07369649        1.57793838 </code></pre>
</div>
</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><code>exp(coef(model))</code> is all you need to turn the log-odds into <strong>odds ratios</strong> — the numbers you actually report. (A formatted table version using <code>tbl_regression()</code> is in the appendix.)</p>
</div>
</div>
</div>
</section>
<section id="model-significance-χ²-and-r²-for-logistic" class="slide level2">
<h2>Model significance (χ²) and R² for logistic</h2>
<p><code>glm()</code> doesn’t print a χ² or an R², so we ask <code>DescTools::PseudoR2()</code> for them. <strong>G2</strong> is the model χ² (goodness-of-fit test vs.&nbsp;a no-predictor model); <strong>Nagelkerke</strong> is the pseudo-R² most commonly reported:</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>DescTools<span class="sc">::</span><span class="fu">PseudoR2</span>(life_model5,</span>
<span id="cb29-2"><a></a>                    <span class="at">which =</span> <span class="fu">c</span>(<span class="st">"G2"</span>, <span class="st">"Nagelkerke"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>         G2  Nagelkerke 
906.9076503   0.2221449 </code></pre>
</div>
</div></div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>There are several pseudo-R² flavours (McFadden, Cox-Snell, …). Pick one and be consistent — <strong>Nagelkerke</strong> is a safe default. <em>(The full list, and how to compute the χ² by hand, are in the appendix.)</em></p>
</div>
</div>
</div>
</section>
<section id="possible-interpretation-of-the-result" class="slide level2">
<h2>Possible interpretation of the result</h2>
<p><strong>Possible interpretation:</strong></p>
<p><em>(The intercept isn’t typically interpreted as an odds ratio, so we’ll ignore that for now)</em></p>
<blockquote>
<p>A logistic regression was performed to ascertain the effects of freedom of choice on the likelihood that individuals will be satisfied with life versus not satisfied. The logistic regression model was statistically significant, χ² (1, N = [N]) = [χ²], p &lt; .001.</p>
</blockquote>
<blockquote>
<p>The model explained [Nagelkerke R²]% (Nagelkerke R²) of the variance in life satisfaction. Freedom of choice was associated with [increased/decreased] likelihood of being satisfied with life (OR = [OR], 95% CI [[lower], [upper]], p &lt; .001), indicating that for each one-unit increase in freedom of choice (1-10), the odds of being satisfied with life changed by [OR-1 as %]%.</p>
</blockquote>

<aside><div>
<p>More on interpreting Odds Ratio: <a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/" class="uri">https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/</a></p>
</div></aside></section>
<section id="recap---why-do-i-need-to-report-these" class="slide level2">
<h2>Recap - why do I need to report these?</h2>
<ul>
<li class="fragment"><p>χ² (Chi-squared) goodness of fit tests whether your model fits the data significantly better than a null model (model with no predictors).</p></li>
<li class="fragment"><p>“Standard” R-squared isn’t typically reported for logistic regression because it’s not as meaningful as it is in linear regression. But we do still want to see how much of the variance in the data can be explained by the model.</p></li>
<li class="fragment"><p>Pseudo R-squared tries to mimic traditional R-squared by showing how much of the variation in the outcome your model explains, but it’s adjusted to work with binary outcomes. It’s sort of answering the question of “How well does my model explain the data?”</p></li>
<li class="fragment"><p>It is possible to have a significant χ² (meaning your model is statistically significant and better than nothing) but a low Pseudo R-squared (showing it still doesn’t explain much variation). This isn’t contradictory - it just means your model is better than random guessing but there’s still a lot of unexplained variation. (Pretty common in social sciences; after all, human behaviours are complex!)</p></li>
</ul>
</section>
<section id="fyi---irl-sample-of-reporting-logistic-regression" class="slide level2">
<h2>FYI - IRL sample of reporting Logistic Regression</h2>
<p>Below is a sample of how you may want to narrate your result. Note the resulting values mentioned in the paragraph below.</p>
<p><img data-src="images/logreg-reporting.jpg"></p>
<p>In a nutshell, you will most likely have to mention the p-value, the coefficients (for linear regressions), the Odd Ratios (for logistic regression) with the confidence intervals, the chi-squared (χ²), and the R-squared. You should also include these information in your regression table.</p>

<aside><div>
<p>The screenshot is retrieved from <a href="https://statistics.laerd.com/spss-tutorials/binomial-logistic-regression-using-spss-statistics.php" class="uri">https://statistics.laerd.com/spss-tutorials/binomial-logistic-regression-using-spss-statistics.php</a></p>
</div></aside></section>
<section id="binary-logistic-regression-one-categorical-predictor" class="slide level2">
<h2>Binary Logistic Regression: One Categorical Predictor</h2>
<p><strong>Research Question</strong>: Does <strong>marital status</strong> affect the likelihood of being satisfied with life?</p>
<ul>
<li>The outcome/DV (<span class="math inline">\(Y\)</span>): <code>satisfied</code></li>
<li>The predictor/IV (<span class="math inline">\(X\)</span>): <code>marital_status</code> - let’s set “Single” as the reference category!</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>wvs_cleaned <span class="ot">&lt;-</span> wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a></a>    <span class="fu">mutate</span>(<span class="at">marital_status =</span> <span class="fu">relevel</span>(marital_status, <span class="at">ref =</span> <span class="st">"Single"</span>))</span>
<span id="cb31-3"><a></a></span>
<span id="cb31-4"><a></a>life_model6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(satisfied <span class="sc">~</span> marital_status,</span>
<span id="cb31-5"><a></a>                      <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb31-6"><a></a>                      <span class="at">data =</span> wvs_cleaned)</span>
<span id="cb31-7"><a></a></span>
<span id="cb31-8"><a></a><span class="fu">summary</span>(life_model6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="binary-logistic-regression-one-categorical-predictor-output" class="slide level2 output-location-slide"><h2>Binary Logistic Regression: One Categorical Predictor</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = satisfied ~ marital_status, family = "binomial", 
    data = wvs_cleaned)

Coefficients:
                                         Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                               0.27975    0.05405   5.175 2.27e-07
marital_statusMarried                     0.38281    0.06546   5.848 4.97e-09
marital_statusWidowed                     0.16494    0.15749   1.047    0.295
marital_statusSeparated                  -0.27975    0.50291  -0.556    0.578
marital_statusDivorced                   -0.09743    0.16543  -0.589    0.556
marital_statusLiving together as married -0.21723    0.25590  -0.849    0.396
                                            
(Intercept)                              ***
marital_statusMarried                    ***
marital_statusWidowed                       
marital_statusSeparated                     
marital_statusDivorced                      
marital_statusLiving together as married    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6739.0  on 5101  degrees of freedom
Residual deviance: 6695.1  on 5096  degrees of freedom
AIC: 6707.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">exp</span>(<span class="fu">coef</span>(life_model6))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             (Intercept) 
                               1.3227953 
                   marital_statusMarried 
                               1.4664008 
                   marital_statusWidowed 
                               1.1793208 
                 marital_statusSeparated 
                               0.7559748 
                  marital_statusDivorced 
                               0.9071698 
marital_statusLiving together as married 
                               0.8047474 </code></pre>
</div>
</div></section><section id="get-the-χ²-and-r²" class="slide level2">
<h2>Get the χ² and R²</h2>
<p>Same as before: <strong>G2</strong> is the model χ² (goodness-of-fit), <strong>Nagelkerke</strong> is the pseudo-R² we’ll report.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>DescTools<span class="sc">::</span><span class="fu">PseudoR2</span>(life_model6,</span>
<span id="cb35-2"><a></a>                    <span class="at">which =</span> <span class="fu">c</span>(<span class="st">"G2"</span>, <span class="st">"Nagelkerke"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         G2  Nagelkerke 
43.84588476  0.01167253 </code></pre>
</div>
</div>
</section>
<section id="narrating-the-results-1" class="slide level2">
<h2>Narrating the results</h2>
<p><strong>Possible interpretation:</strong></p>
<p><em>(The intercept isn’t typically interpreted as an odds ratio, so we’ll ignore that for now)</em></p>
<blockquote>
<p>A logistic regression was performed to ascertain the effects of marital status on the likelihood that individuals will be satisfied with life versus not satisfied. The logistic regression model was statistically significant, χ²(5, N = 5102) = 43.9, p &lt; .001.</p>
</blockquote>
<blockquote>
<p>The model explained about 1.2% of the variance in life satisfaction (Nagelkerke R² ≈ 0.012 — read it off the <code>PseudoR2()</code> output). Compared to <strong>single</strong> respondents (the reference group), <strong>married</strong> respondents had significantly higher odds of being satisfied with life (OR = 1.47, 95% CI [1.29, 1.67], p &lt; .001) — roughly 47% higher odds. None of the other categories (widowed, divorced, separated, or living together) differed significantly from single respondents (all p &gt; .05).</p>
</blockquote>

<aside><div>
<p>More on logistic regression: <a href="https://stats.oarc.ucla.edu/r/dae/logit-regression/" class="uri">https://stats.oarc.ucla.edu/r/dae/logit-regression/</a></p>
</div></aside></section>
<section id="presenting-logistic-results-with-huxtable" class="slide level2 scrollable">
<h2>Presenting logistic results with huxtable</h2>
<p><code>huxreg()</code> works for <code>glm()</code> models too — here comparing both logistic models:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">huxreg</span>(<span class="st">"freedom of choice"</span> <span class="ot">=</span> life_model5, <span class="st">"marital status"</span> <span class="ot">=</span> life_model6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Heads-up: <code>huxreg()</code> shows the <strong>raw log-odds</strong> coefficients for a <code>glm</code>, <em>not</em> odds ratios — remember <code>exp(coef(model))</code> for the ORs you report. It also omits pseudo-R², so note that separately from <code>PseudoR2()</code>.</p>
</div>
</div>
</div>
</section>
<section id="presenting-logistic-results-with-huxtable-output" class="slide level2 scrollable output-location-slide"><h2>Presenting logistic results with huxtable</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<table class="huxtable" data-quarto-disable-processing="true" style="margin-left: auto; margin-right: auto;">
<colgroup><col><col><col></colgroup><thead>
<tr>
<th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;"></th><th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;">freedom of choice</th><th class="huxtable-cell huxtable-header" style="text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;">marital status</th></tr>
</thead>
<tbody>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">(Intercept)</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">-2.608 ***</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">0.280 ***</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.120)&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.054)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">freedom_of_choice</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">0.456 ***</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.017)&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">marital_statusMarried</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">0.383 ***</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.065)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">marital_statusWidowed</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">0.165&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.157)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">marital_statusSeparated</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">-0.280&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.503)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">marital_statusDivorced</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">-0.097&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">(0.165)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">marital_statusLiving together as married</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">-0.217&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;"></th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;">(0.256)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">N</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">5102&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;">5102&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;">logLik</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">-2916.042&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;">-3347.573&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" style="border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;      font-weight: normal;">AIC</th><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;">5836.084&nbsp;&nbsp;&nbsp;&nbsp;</td><td class="huxtable-cell" style="text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;">6707.146&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th class="huxtable-cell huxtable-header" colspan="3" style="border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;">*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</th></tr>
</tbody>
</table>
</div>
</div></section><section id="lets-try-this-logistic-regression-exercise-5-mins" class="slide level2">
<h2>Let’s try this Logistic Regression exercise! (5 mins)</h2>
<p>Create a regression model called <code>life_model7</code> that predicts the likelihood of being satisfied with life based on <code>sex</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>life_model7 <span class="ot">&lt;-</span> <span class="fu">glm</span>(satisfied <span class="sc">~</span> sex,</span>
<span id="cb38-2"><a></a>                  <span class="at">family =</span> <span class="st">"binomial"</span>, </span>
<span id="cb38-3"><a></a>                  <span class="at">data =</span> wvs_cleaned) </span>
<span id="cb38-4"><a></a></span>
<span id="cb38-5"><a></a><span class="fu">summary</span>(life_model7)</span>
<span id="cb38-6"><a></a><span class="fu">exp</span>(<span class="fu">coefficients</span>(life_model7))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section></section>
<section>
<section id="bonus-show-and-tell-quarto" class="title-slide slide level1 center">
<h1>Bonus show-and-tell: Quarto</h1>

</section>
<section id="what-are-markdown-r-markdown-and-quarto" class="slide level2">
<h2>What are Markdown, R Markdown, and Quarto?</h2>
<ul>
<li class="fragment"><strong>Markdown</strong> — a lightweight, readable way to write formatted text (no messy HTML or LaTeX). Files end in <code>.md</code>.</li>
<li class="fragment"><strong>R Markdown</strong> — Markdown <strong>+ live R code chunks</strong>, so text, code, and output (tables, plots) live in one document (<code>.Rmd</code>).</li>
<li class="fragment"><strong>Quarto</strong> — Posit’s next-generation, multi-language successor to R Markdown. It renders most <code>.Rmd</code> files unchanged and can output HTML, Word, PDF, slides, and whole websites.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Fun fact: this entire course website <strong>and</strong> these slides are built in Quarto! <em>(A quick R-Scripts-vs-Quarto comparison is in the appendix.)</em></p>
</div>
</div>
</div>
</section>
<section id="how-it-all-works" class="slide level2">
<h2>How it all works</h2>

<img data-src="images/quarto-rendering.png" class="r-stretch quarto-figure-center"><p class="caption">Illustration by Allison Horst (www.allisonhorst.com)</p></section>
<section id="if-you-are-interested-to-learn-more-about-this" class="slide level2">
<h2>If you are interested to learn more about this…</h2>
<p>SMU Libraries regularly host Quarto workshops every semester from week 2 to week 6, taught by Prof Kam Tin Seong.</p>
<p>Keep a lookout for these titles:</p>
<ul>
<li>R Ep.1: Making Your Research Reproducible with Quarto in RStudio</li>
<li>R Ep.7: Creating Awesome Web Slides in Quarto with Revealjs</li>
<li>R Ep.9: Building Website and Blog with Quarto</li>
</ul>
</section></section>
<section>
<section id="best-practices-more-resources" class="title-slide slide level1 center">
<h1>Best Practices + More Resources</h1>

</section>
<section id="r-best-practices" class="slide level2">
<h2>R Best Practices</h2>
<ul>
<li><p>Use <code>&lt;-</code> for assigning values to objects.</p>
<ul>
<li>Only use <code>=</code> when passing values to a function parameter.</li>
</ul></li>
<li><p><u><strong>Do not alter your raw data</strong></u>; save your wrangled/cleaned data into a new file and keep it separate from the raw data.</p></li>
<li><p>Make use of R projects to organize your data and make it easier to send over to your collaborators.</p>
<ul>
<li>Having said that, when it comes to coding project, the best way to collaborate is using GitHub or similar platforms.</li>
</ul></li>
<li><p>Whenever possible and makes sense for your project, follow the common convention when naming your objects, scripts, and functions. One guide that you can follow is <a href="https://style.tidyverse.org/">Hadley Wickham’s tidyverse style guide</a>.</p></li>
</ul>
</section>
<section id="references-for-apa-guidelines-on-reporting-statistics" class="slide level2">
<h2>References for APA Guidelines on Reporting statistics</h2>
<p>Do check with your professor on how closely you should follow the guidelines, or if there is any specific format required.</p>
<ul>
<li><a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">APA Style 7th Edition Numbers and Statistics Guide</a></li>
<li><a href="https://psych.uw.edu/storage/writing_center/stats.pdf">University of Washington - Reporting Results of Common Statistical Tests in APA Format</a></li>
<li><a href="https://about.illinoisstate.edu/mshesso-test2/reporting-statistics-in-apa-style/">Illinois State University - A Short Guide to Handling Numbers and Statistics in APA Format (in 6th Edition)</a></li>
<li><a href="https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#regression">Statistic Tables in APA recommended format</a></li>
</ul>
</section></section>
<section>
<section id="one-last-thing-you-own-the-analysis" class="title-slide slide level1 center">
<h1>One last thing: you own the analysis</h1>

</section>
<section id="because-the-ai-said-so-is-not-an-answer" class="slide level2">
<h2>“Because the AI said so” is not an answer</h2>
<p>Over five sessions you’ve learned to import, wrangle, visualize, and run real inferential tests in R. An AI assistant can now generate all of that code for you in seconds — and often it will do a decent job.</p>
<p>So what’s <em>your</em> job now? The parts the AI <strong>can’t be accountable for</strong>:</p>
<ul>
<li class="fragment"><strong>Define</strong> the research questions and thus test for your variables — and being able to say <em>why</em>.</li>
<li class="fragment"><strong>Checking</strong> whether the result can be reasonably trusted — assumptions, sample size, plain common sense.</li>
<li class="fragment"><strong>Interpreting</strong> the output honestly.</li>
<li class="fragment"><strong>Disclosing</strong> the limitations plainly, even when they’re inconvenient.</li>
</ul>
<p>When your professor, a reviewer, or a future employer asks <em>“why did you run this analysis, and can I trust it?”</em> — <strong>“Claude/ChatGPT told me to”</strong> is not a defensible answer. <strong>You</strong> are accountable for the work that carries your name.</p>
</section></section>
<section>
<section id="thank-you-for-your-participation" class="title-slide slide level1 center">
<h1>Thank you for your participation 😄</h1>
<div class="columns">
<div class="column" style="width:35%;">
<p><img data-src="images/wedidit.webp"></p>
</div><div class="column" style="width:65%;">
<p>All the best for your studies and academic journey! <em>(manifesting excellent grades + internship for everyone who attended the workshop)</em></p>
<p>Need help with R or Quarto? Please don’t hesitate to contact us at <a href="mailto:bellar@smu.edu.sg">bellar@smu.edu.sg</a> or <a href="mailto:weixia@smu.edu.sg">weixia@smu.edu.sg</a></p>
</div></div>
</section>
<section id="quiz-time-compulsory" class="slide level2">
<h2>Quiz Time! (compulsory)</h2>
<p>Scan the QR Code below to assess your understanding of regression analysis and reporting results using R in social sciences. All questions are required and each is worth 1 mark.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="https://forms.cloud.microsoft/r/re0mfH7Y3r"><img data-src="images/RegressionandPresentingYourResultQRCode.png" class="quarto-figure quarto-figure-center" alt="Quiz QR Code: https://forms.cloud.microsoft/r/re0mfH7Y3r" width="400"></a></p>
</figure>
</div>
<figcaption>Quiz QR Code: &lt;https://forms.cloud.microsoft/r/re0mfH7Y3r&gt;</figcaption>
</figure>
</div>
</section>
<section id="post-workshop-survey" class="slide level2">
<h2>Post-workshop survey</h2>
<p>Please scan this QR code or click on the link below to fill in the post-workshop survey. It should not take more than 2-3 minutes.</p>
<p>Survey link: <a href="https://smusg.asia.qualtrics.com/jfe/form/SV_9Xhn2NY4vkA4GaO" class="uri">https://smusg.asia.qualtrics.com/jfe/form/SV_9Xhn2NY4vkA4GaO</a></p>

<img data-src="images/post-workshop-qrcode.png" width="500" class="r-stretch"></section></section>
<section>
<section id="appendix" class="title-slide slide level1 center">
<h1>Appendix</h1>
<ul>
<li>Prettier tables with gtsummary &amp; apaTables</li>
<li>gtsummary summary tables</li>
<li>Computing the logistic χ² by hand</li>
<li>Other pseudo-R² methods</li>
<li>R Scripts vs Quarto</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>We used <strong>huxtable</strong> in the main session. These <code>gtsummary</code> / <code>apaTables</code> alternatives produce nicer output but have heavier dependencies — the code here is shown <strong>for reference, not executed</strong> — run it live in RStudio (after <code>install.packages()</code> + <code>library()</code>) to see the tables.</p>
</div>
</div>
</div>
</section>
<section id="presenting-regression-tables-gtsummary-tbl_regression" class="slide level2">
<h2>Presenting regression tables: gtsummary (<code>tbl_regression</code>)</h2>
<p><code>tbl_regression()</code> makes clean, publication-style tables. For logistic models, <code>exponentiate = TRUE</code> reports <strong>odds ratios</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb39-2"><a></a></span>
<span id="cb39-3"><a></a><span class="co"># linear model</span></span>
<span id="cb39-4"><a></a>life_model2 <span class="sc">|&gt;</span> <span class="fu">tbl_regression</span>() <span class="sc">|&gt;</span> <span class="fu">bold_p</span>()</span>
<span id="cb39-5"><a></a></span>
<span id="cb39-6"><a></a><span class="co"># logistic model — odds ratios</span></span>
<span id="cb39-7"><a></a>life_model5 <span class="sc">|&gt;</span> <span class="fu">tbl_regression</span>(<span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">bold_p</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>These render in RStudio’s <strong>Viewer</strong> pane — select the table, copy (Ctrl/Cmd + C), and paste into Word or Google Docs.</p>
</div>
</div>
</div>
</section>
<section id="table-packages-apatables" class="slide level2">
<h2>Table packages: apaTables</h2>
<p><code>apaTables</code> generates APA-formatted tables for correlation, ANOVA, and regression. Limited customisation. The online docs are for the development version (not what <code>install.packages()</code> gives you), so lean on the vignette. <a href="https://dstanley4.github.io/apaTables/index.html"><strong>Documentation here</strong></a></p>
<p>Example: a correlation table for <code>life_satisfaction</code>, <code>financial_satisfaction</code>, and <code>freedom_of_choice</code></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">library</span>(apaTables)</span>
<span id="cb40-2"><a></a></span>
<span id="cb40-3"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a></a>    <span class="fu">select</span>(life_satisfaction, financial_satisfaction, freedom_of_choice) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a></a>    <span class="fu">apa.cor.table</span>(<span class="at">table.number =</span> <span class="dv">1</span>, <span class="at">filename =</span> <span class="st">"fig-output/table-cor.doc"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This creates a Word document with the table already formatted in APA style.</p>
</section>
<section id="table-packages-gtsummary-summary-tables" class="slide level2">
<h2>Table packages: gtsummary summary tables</h2>
<p>Besides <code>tbl_regression()</code>, <code>gtsummary</code> can build descriptive / mean-difference tables with <code>tbl_summary()</code>. <a href="https://www.danieldsjoberg.com/gtsummary/index.html"><strong>Documentation here</strong></a></p>
<p>Example: mean-differences table grouped by <code>sex</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb41-2"><a></a></span>
<span id="cb41-3"><a></a>wvs_cleaned <span class="sc">|&gt;</span></span>
<span id="cb41-4"><a></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(life_satisfaction, financial_satisfaction, freedom_of_choice, sex) <span class="sc">|&gt;</span></span>
<span id="cb41-5"><a></a>    <span class="fu">tbl_summary</span>(<span class="at">by =</span> sex) <span class="sc">|&gt;</span></span>
<span id="cb41-6"><a></a>    <span class="fu">add_difference</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="computing-the-logistic-χ²-by-hand" class="slide level2">
<h2>Computing the logistic χ² by hand</h2>
<p>We used <code>PseudoR2(..., which = "G2")</code> to get the model χ². If you ever need it manually, it’s the drop in deviance from the null model:</p>
<ul>
<li>χ² = Null deviance − Residual deviance (both from the <code>summary()</code> output)</li>
<li>df = Null df − Residual df (= number of predictors)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="co"># Replace with the values from your summary() output</span></span>
<span id="cb42-2"><a></a>chi_sq <span class="ot">&lt;-</span> NULL_DEVIANCE <span class="sc">-</span> RESIDUAL_DEVIANCE</span>
<span id="cb42-3"><a></a><span class="fu">pchisq</span>(chi_sq, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># p-value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="other-pseudo-r²-methods" class="slide level2">
<h2>Other pseudo-R² methods</h2>
<p>If you specifically need a different pseudo-R² (e.g.&nbsp;McFadden, Cox-Snell), <code>PseudoR2()</code> can return them all at once:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>DescTools<span class="sc">::</span><span class="fu">PseudoR2</span>(life_model5,</span>
<span id="cb43-2"><a></a>                    <span class="at">which =</span> <span class="st">"all"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       McFadden     McFaddenAdj        CoxSnell      Nagelkerke   AldrichNelson 
      0.1345762       0.1339826       0.1628528       0.2221449       0.1509272 
VeallZimmermann           Efron McKelveyZavoina            Tjur             AIC 
      0.2651922       0.1844291       0.2233348       0.1772867    5836.0841311 
            BIC          logLik         logLik0              G2 
   5849.1589069   -2916.0420655   -3369.4958907     906.9076503 </code></pre>
</div>
</div>
</section>
<section id="r-scripts-vs-quarto" class="slide level2">
<h2>R Scripts vs Quarto</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>R Scripts</strong></p>
<ul>
<li><p>Great for quick debugging, experiment</p></li>
<li><p>Preferred format if you are archiving your code to GitHub or data repository</p></li>
<li><p>More suitable for “production” tasks e.g.&nbsp;automating your data cleaning and processing, custom functions, etc.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Quarto</strong></p>
<ul>
<li><p>Great for report and presentation to showcase your research insights/process as it integrates code, narrative text, visualizations, and results.</p></li>
<li><p>Very handy when you need your report in multiple format, e.g.&nbsp;in Word and PPT.</p></li>
<li><p>Fun fact: the course website and slides are all made in Quarto</p></li>
</ul>
</div></div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/smu logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://smu-libraries.github.io/r-socsci/">Introductory R for Social Science</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/smu-libraries\.github\.io\/r-socsci\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>