project:
  type: website

website:
  title: "Introductory R for Social Sciences"
  page-footer: "Made with love and [Quarto](https://quarto.org/) by [Bella Ratmelia](https://bellaratmelia.github.io/) - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dataset.qmd
        text: Dataset
      - href: coc.qmd
        text: Code of conduct
      - sidebar:resources
        
  sidebar:
    - id: resources
      title: "Resources"
      contents:
        - href: resources.qmd
          text: "Further Readings"
        - href: exercises.qmd
          text: "Exercises for your own practice"
        - href: "https://bellaratmelia.github.io/2024-08-Rworkshop/"
          text: "Past workshop - AY 24/25 Term 1 (Aug - Sep)"
        - href: "https://bellaratmelia.github.io/2025-01-Rworkshop/"
          text: "Past workshop - AY 24/25 Term 2 (Jan - Feb)"
        
  google-analytics:
    tracking-id: "G-G5L1RGYC4H"
    anonymize-ip: true
    storage: none

format:
  html:
    theme: 
      - flatly
      - custom.scss
    toc: true

  revealjs: 
    theme: [default, custom.scss]
    width: 1600
    height: 900
    slide-number: true
    footer: "[Introductory R for Social Science](https://smu-libraries.github.io/r-socsci/)"
    logo: "images/smu logo.png"
    fig-height: 7
    fig-width: 14
    

execute:
  freeze: auto
